---
title: "FITNESS patient timeline"
author: "Rebecca Hoyd"
date: "7/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2) 
library(dplyr)
library(magrittr)
library(ggnewscale)
```

```{r}
# Processed in exploratory/scripts
timein <- readRDS("../../../exploratory/data/timeline_all-lung-clinic.RDS")
```

```{r}
timein$samples <- 
  timein$samples %>%
  rename("Toxicity.Grade" = "max.gade") 

timein$ribbon <- 
  timein$ribbon %>%
  mutate(treatment_dummy = case_when(summarise_treatment == "chemo" ~ "b",
                                     summarise_treatment == "chemo,io" ~ "c",
                                     summarise_treatment == "io" ~ "d",
                                     summarise_treatment == "targeted" ~ "e"))

timein$recist <- 
  timein$recist %>%
  mutate(RECIST = if_else(grepl("CR|PR", RECIST_month3),
                          true = "R",
                          false = if_else(grepl("SD|PD", RECIST_month3),
                                          true = "NR",
                                          false = RECIST_month3)
                          ),
         RECIST.dummy = ifelse(RECIST == "NR", "a", "f")
         )

ggplot() +
  geom_rect(data = timein$ribbon,
            aes(ymin = rib.low, ymax = rib.hi,
                fill = treatment_dummy),
            alpha = .5,
            xmin = 0, xmax = 755) +
  geom_segment(data = timein$timeline, 
               aes(x = 0,
                   xend = max.date, 
                   y = patnum,
                   yend = patnum)) +
  # Label collections
  geom_point(data = timein$samples, 
             aes(x = elapsed.days,
                 y = patnum,
                 shape = fct_relevel(sampletype, "stool"),
                 color = Toxicity.Grade)) +
  scale_color_distiller(type = "seq",
                        palette = "Greys", na.value = "black") +
 
  new_scale_color() +

  # Label RECIST 
  geom_point(data = timein$recist,
             aes(x = 750,
                 y = patnum,
                 color = RECIST.dummy),
             shape = 15,
             size = 2.4) +
  # scale_color_manual(values = c("red", "dodgerblue"),
  #                   name = "Response") +
  scale_fill_viridis_d(name = "Treatment", 
                       breaks = c("a", "b", "c", "d", "e", "f"),
                       labels = c("NR", "Chemo", "Chemo+IO", "IO", "Targeted", "R"),
                       aesthetics = c("color", "fill")
                       ) +
    # scale_color_viridis_d(name = "Response", 
    #                    breaks = c("a", "b", "c", "d", "e", "f"),
    #                    labels = c("NR", "Chemo", "Chemo+IO", "IO", "Targeted", "R") 
    #                    ) +
  scale_shape(name = "Event type") +
  scale_y_continuous(breaks = timein$ribbon$patnum, 
                     labels = timein$ribbon$patient.id) +
  labs(x = "Days", 
       y = "Patient") +
  theme_classic() +
  theme(axis.text.y = element_blank())

ggsave("../figures/timeline_fitness-patients.png",
       height = 5, width = 8)

# Save taller so the full legend can be retrieved and manually added
ggsave("../figures/timeline_fitness-patients_for-full-legend.png",
       height = 10, width = 8)
```

