---
title: "longitudinal with fixed effects"
author: "Rebecca Hoyd"
date: "1/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(readxl)
library(lme4)
library(lmerTest)
library(broom)
library(rlist)
library(ggforce)
library(modelsummary)
source("00-paths.R")
```

# Load data

```{r}

clin <- read.csv(file.path(paths$t.drive, "data","derived", "clinical-OC-matched_resolved_limited.csv"),
                 stringsAsFactors = F)
clin.withdate <- read.csv(file.path(paths$controlled, "clinical-OC-matched_resolved.csv"),
                          stringsAsFactors = F)

ICI.meds.raw <- read_excel("../data/FITNESS_TreatmentCategories_8.23.21.xlsx")

```

# Set up modeling

## Get + format modelling data

```{r prepare clinical with fixed effects}
ICI.meds <- ICI.meds.raw %>%
  rename(ici.nums = ...1,
         ici.name = `Category (chemo, chemo + io, io, targeted, targeted+chemo)`) %>%
  mutate(ici.name =str_replace_all(ici.name, "\\s", ""))

clin.timein <- clin.withdate %>%
  mutate(ici.nums = as.character(ifelse(!is.na(tx_reg_1_2), tx_reg_1_2, tx_reg_1))) %>%
  select(patient.id, sequence.id, redcap_event_name, ici.nums) %>%
  drop_na(ici.nums) %>%
  mutate(ici.nums = as.numeric(ici.nums)) %>%
  left_join(ICI.meds) %>%
  mutate(ici.name = ifelse(ici.name == "n/a", "Not.ICI", ici.name))
```

```{r get and format microbe data}
mics <- read.table(file.path(paths$t.drive, "data","derived","merged_metaphlan_output.txt"), sep = "\t", header = T, stringsAsFactors = F)

mics.form <- mics %>%
  select(-NCBI_tax_id) %>%
  mutate(clade_name = make.names(clade_name)) %>%
  gather(-clade_name, key = "sequence.id", value = "RA") %>%
  spread(key = clade_name, value = RA)

mic.names <- colnames(mics.form[,-1])
```

```{r combine all variables}
modelin <- clin.withdate %>%
  select(patient.id, redcap_event_name, sppb_score, promis_score, 
         iadl_score, tug, stool_sample_date, sequence.id) %>%
  filter(!is.na(sppb_score) &!is.na(stool_sample_date)) %>%
  mutate(stool_sample_date = as.Date(stool_sample_date)) %>%
  group_by(patient.id) %>%
  mutate(min.date = min(stool_sample_date)) %>%
  ungroup() %>%
  mutate(rel.date = as.numeric(stool_sample_date - min.date)) %>%
  left_join(mics.form)%>%
  left_join(clin.timein)
  
```

## Modeling function


```{r}
long_mods <-function(outcome, mics.vec){
  
  mods <- lapply(mics.vec, function(x) try(lmer(formula = as.formula(paste0(outcome,
                                                                            " ~ ",
                                                                            x,
                                                                            " + rel.date +",
                                                                            " ici.name +",
                                                                            " (1|patient.id)")),
                                                data = modelin)))
  names(mods) <- mics.vec
  mods.coef <- lapply(mics.vec, function(x) try(summary(mods[[x]])$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = "microbe") %>%
    filter(microbe == x)))
mods.gof <- lapply(mics.vec, function(x) get_gof(mods[[x]]) %>%
                     as.data.frame() %>%
                     mutate(microbe = x)) %>%
  bind_rows()
mods.clean <- bind_rows(mods.coef) %>%
  arrange(`Pr(>|t|)`) %>%
  mutate(padj = p.adjust(`Pr(>|t|)`, method = "fdr")) %>%
  left_join(mods.gof)
return(mods.clean)
}
```

## Run and save

```{r}
sppb.mods <- long_mods("sppb_score", mic.names)
promis.mods <- long_mods("promis_score", mic.names)
iadl.mods <- long_mods("iadl_score", mic.names)
timedupgo <- long_mods("tug", mic.names)

sppb.mods.lab <- sppb.mods %>%
  mutate(GA = "SPPB")
promis.mods.lab <- promis.mods %>%
  mutate(GA = "PROMIS")
iadl.mods.lab <- iadl.mods %>%
  mutate(GA = "IADL")
timedupgo.mods.lab <- timedupgo %>%
  mutate(GA = "TUG")

alltests <- bind_rows(sppb.mods.lab, promis.mods.lab, iadl.mods.lab, timedupgo.mods.lab)
```

```{r}
write.csv(sppb.mods, "../data/model_long-treat_sppb.csv", row.names = F)
write.csv(promis.mods, "../data/model_long-treat_promis.csv", row.names = F)
write.csv(iadl.mods, "../data/model_long-treat_iadl.csv", row.names = F)
write.csv(timedupgo, "../data/model_long-treat_timed-up-go.csv", row.names = F)

write.csv(alltests, "../tables/S1_fixed-effects-models.csv", row.names = F)
```

