---
title: "Table2 Summary Statistics"
output: html_document
date: "2023-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
source("00-paths.R")
```

# Load data

```{r}
clin.withdate <- read.csv(file.path(paths$controlled, "CoRR5512FITNESSCalcu_DATA_2023-02-22_1052.csv"), stringsAsFactors = F)
```

# Select correct samples

```{r}
baseline <- clin.withdate %>%
  filter(enrollment_date != "" & grepl("arm_2", redcap_event_name)) %>%
  filter(!id %in% c(26,51))
```

# PROMiS

```{r}
# Checking for correct sample size
table(!is.na(baseline$promis_score))
```

```{r}
promis <- summary(baseline$promis_score)

paste0(promis[["Median"]], "(", promis[["1st Qu."]], ",", promis[["3rd Qu."]], ")")
```

# EORTC

```{r}
# Checking for correct sample size
table(!is.na(baseline$eortc_score))
```

```{r}
eortc <- summary(baseline$eortc_score)

paste0(eortc[["Median"]], "(", eortc[["1st Qu."]], ",", eortc[["3rd Qu."]], ")")
```

# FS7

```{r}
fa7.score.comps <- c("fa_bathe",
"fa_walkaround",
"fa_dressing",
"fa_chair",
"fa_eat",
"fa_grooming",
"fa_toileting")

fa7.tmp <- baseline %>%
  select(id, fa7.score.comps) %>%
  mutate(fa7 = fa_bathe + fa_walkaround + fa_dressing + fa_chair + fa_eat + fa_grooming + fa_toileting)
```

```{r}
table(!is.na(fa7.tmp$fa7))
```

```{r}
fa7 <- summary(fa7.tmp$fa7)

paste0(fa7[["Median"]], "(", fa7[["1st Qu."]], ",", fa7[["3rd Qu."]], ")")
```

# FS13

```{r}
fa13.score.comps <- c("fa_bathe",
"fa_walkaround",
"fa_dressing",
"fa_chair",
"fa_eat",
"fa_grooming",
"fa_toileting",
"fa_lifting",
"fa_shop",
"fa_housework",
"fa_mealprep",
"fa_medications",
"fa_finances"
)

fa13.tmp <- baseline %>%
  select(id, fa13.score.comps) %>%
  mutate(fa13 = fa_bathe + fa_walkaround + fa_dressing + fa_chair + fa_eat + fa_grooming + fa_toileting + fa_lifting + fa_shop + fa_housework + fa_mealprep + fa_medications + fa_finances)
```

```{r}
table(!is.na(fa13.tmp$fa13))
```

```{r}
fa13 <- summary(fa13.tmp$fa13)

paste0(fa13[["Median"]], "(", fa13[["1st Qu."]], ",", fa13[["3rd Qu."]], ")")
```

# BLESSED
```{r}
table(!is.na(baseline$blessed_score))
```

```{r}
blessed <- summary(baseline$blessed_score)

paste0(blessed[["Median"]], "(", blessed[["1st Qu."]], ",", blessed[["3rd Qu."]], ")")
```

# SPPB

```{r}
table(!is.na(baseline$sppb_score))
```

```{r}
sppb <- summary(baseline$sppb_score)
paste0(sppb[["Median"]], "(", sppb[["1st Qu."]], ",", sppb[["3rd Qu."]], ")")
```
