#PBS -N download_fitness_9
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_a6c2ac215b094427/SQ6912.fastq.gz?filename=FF05466614.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=QX7fCf4XtbHC8sMkR0CxKUqy%2B68%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_ab2270c63e2f4665/SQ6970.fastq.gz?filename=FF05466297.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Yn3mixkwGz2yO38eBtbptd8enMU%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_08b0d48d33cd42d0/SQ6927.fastq.gz?filename=FF05466131.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=cpzOb4QEJP2hrsL2F1fFUKIG%2BZM%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_12f5b753a6ef4dfc/SQ6972.fastq.gz?filename=FF05466260.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=0gxHyhuBTGK3MSw%2FMs94jOejvBA%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_387db859c5e74bd1/SQ6947.fastq.gz?filename=FF05466149.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=b4Sfv1Udij4PdcQ2ktwBay5aq40%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_ed5e8050df76495d/SQ6926.fastq.gz?filename=FF05466382.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Yjq1I9m5BfnH%2Baq4TOs0q2C6160%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_1cce8a33d1ed41df/SQ6939.fastq.gz?filename=FF05466286.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=OVxki59qYQpf92M%2BQCwc92CHL2Y%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_faaef70f0d5c40ae/SQ6959.fastq.gz?filename=FF05464228.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=sQAG8lQ9Rr96LmCV5DdYpSpR11E%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_33a2dcb10a3b42ad/SQ6942.fastq.gz?filename=FF05466308.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=rvxHu%2BfhTLVcs%2FL9l2kg7xoYGYc%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_e93c5a0535d045ae/SQ6917.fastq.gz?filename=FF05465981.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=VwzT2s%2BkvVBxP8ut21tCo1fbW9k%3D

