#PBS -N download_fitness_1
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_28bbee120f124072/SQ6154.fastq.gz?filename=FF05464387.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=%2Fuj%2FLZBvCr1hQicTT2edmn9okJk%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_6b9192c133ee471d/SQ6982.fastq.gz?filename=FF05466305.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=E71OCAHquKznygicbiwZmZQ9cJA%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_983ca678d7754125/SQ6976.fastq.gz?filename=FF05466271.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=YSm4kn7SHNQn6p2oN1RpadpoBeU%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_5da2f1d132a24391/SQ6905.fastq.gz?filename=FF05466314.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=rvRqr0OVLZkiRLQVAv0MBDCOQCg%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_dd220bfaa7724f3b/SQ6922.fastq.gz?filename=FF05466567.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=w9GnBwHdbMsDQu%2FtHEDfk2I7Ovk%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_d33a6b08e4af46ab/SQ6913.fastq.gz?filename=FF05466588.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Pvf3OenuCXKvmjFktR2OpjFePno%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_385bfb38ddf9474c/SQ6158.fastq.gz?filename=FF05466285.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=3BGr%2Fw0xBSNtuvrG7yt%2B%2FoNYb%2FE%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_08af70d7405f460e/SQ6167.fastq.gz?filename=FF05466058.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=XDOiJN7Qgurz%2FBXDy%2BbATeAsgKk%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_111c717fc79448c1/SQ6172.fastq.gz?filename=FF05466302.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=ls%2FBleK5cDEb7qtxFIHQFWMLlcU%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_a1e3545c6a0f4c5c/SQ6984.fastq.gz?filename=FF05466747.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=vF22T2BLsrr%2Fg%2FhD7Tv1BW6AeIo%3D

