#PBS -N download_fitness_10
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_29f91b6df0414601/SQ6903.fastq.gz?response-content-disposition=attachment; filename=FF05466090.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=sknjymHn88VVyW4u%2BSuOUIhxqY4%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_7770a515ab3e4abc/SQ6971.fastq.gz?response-content-disposition=attachment; filename=FF05466080.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=cDnofKM7jBO67YZIcMWzOxmSU2o%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_7ad45183f12345b7/SQ6904.fastq.gz?response-content-disposition=attachment; filename=FF05466751.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=hqzQr6WjpjymBGlKr6YCxXd5oBc%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_be8518b7f04646f1/SQ6935.fastq.gz?response-content-disposition=attachment; filename=FF05466264.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=uTYEQfq0%2BGb6qZ6m6%2FQaNGj6UKU%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_f495437011654349/SQ6924.fastq.gz?response-content-disposition=attachment; filename=FF05464475.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=vCoiTXEvvElMB8OdjeAhtfA6uX8%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_136518c905c447f6/SQ6914.fastq.gz?response-content-disposition=attachment; filename=FF05466158.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=FTpoRMnU9%2FkNcK%2FBvji%2BG9DEa8c%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_0cffb00ea18b46dc/SQ6910.fastq.gz?response-content-disposition=attachment; filename=FF05464532.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=PQTACRqOkxpYxKRs%2BnVBJUVXe9c%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_8b60b67dfdfa4b69/SQ6929.fastq.gz?response-content-disposition=attachment; filename=FF05464166.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=jqiOyqc5Eus47koZ5CR7SNyn90I%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_fb6aa5ec0b5240e4/SQ6986.fastq.gz?response-content-disposition=attachment; filename=FF05466111.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=DYp0GLUfpgIrZ9yWOflmeclSnwA%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_6a7b75ce9ca44868/SQ6979.fastq.gz?response-content-disposition=attachment; filename=FF05464521.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=CxSTOhcP%2Fkj9nImL4q0TYInwRmk%3D

