#PBS -N download_fitness_8
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_6f2eed2c8d0041ab/SQ6954.fastq.gz?filename=FF05464242.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=8QD1H4OoJOeasBD253ot5YwGo8Q%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_1fd457c3e0b44d51/SQ6965.fastq.gz?filename=FF05465989.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=0MGcJnvutnCRuFFp9z%2BMVU4HXAo%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_a9b96b8a1d2d4330/SQ6952.fastq.gz?filename=FF05466738.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=ADkwngQC2KkWBGE%2BJuxVkeOhT34%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_8aa7beefb3c84637/SQ6928.fastq.gz?filename=FF05466196.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Ga0Nv5DoDT6rGT240YEnVVRyoOo%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_c9e3eeacc1cd4cea/SQ6945.fastq.gz?filename=FF05464394.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=jszSbpww4zF3Zure%2FUxsUtH07dM%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_27b29c3af3904ae2/SQ6960.fastq.gz?filename=FF05464165.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Pf5VMMg86mCoivxsabt0gamoF80%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_db8f3a9059b34d70/SQ6933.fastq.gz?filename=FF05466611.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=NAeFDd2Yia7Qb83G1sc74HfxWQ0%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_1389800f6faf4e48/SQ6915.fastq.gz?filename=FF05466254.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=ajzRH6qEku5rfabeC5Ij2D8c53Y%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_f58c9fcda15b4c8a/SQ6932.fastq.gz?filename=FF05466170.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=ZIWamXQcc4pkvkdvGFVKFolTJ1A%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_867d3313c0a847e7/SQ6943.fastq.gz?filename=FF05465968.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=uJj38BlGIj0Q1JoKDSGx4HUjsks%3D

