#PBS -N download_fitness_2
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_09e39ad081c047e2/SQ6164.fastq.gz?response-content-disposition=attachment; filename=FF05466119.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=PPqB%2FiqxF0D1vkXBCn28eyg0ZnE%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_3af6a7215d244580/SQ6160.fastq.gz?response-content-disposition=attachment; filename=FF05466594.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=UadYouRpLTbWMZ7z7sK84%2BJX9FE%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_a539bd9e15ac47bf/SQ6149.fastq.gz?response-content-disposition=attachment; filename=FF05466258.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=5ecpRXKaxIueCI4CMD7TIa9SobQ%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_9872ecad0532403d/SQ6150.fastq.gz?response-content-disposition=attachment; filename=FF05464144.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=deYmvA9WMUHZRPI%2Fo0xgh2aIMOw%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_19972ddc9e4d4e74/SQ6166.fastq.gz?response-content-disposition=attachment; filename=FF05466568.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=AJo4zb106nwRUncWj6a2pRsQkt4%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_e3fa4f4c8a6a4c9f/SQ6157.fastq.gz?response-content-disposition=attachment; filename=FF05466141.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=xXSe50tW5C%2BqZuMovoeqRM7ekOo%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_c22b70dfc3bc459e/SQ6985.fastq.gz?response-content-disposition=attachment; filename=FF05466537.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=zbiL5SUOEZeUwQQhQFFMxnq2GVk%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_59c840a9b59043b7/SQ6978.fastq.gz?response-content-disposition=attachment; filename=FF05466275.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=M8Mj86UP9Pca3dxwZTvSGzVQWe0%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_9a0628e8ee864fc8/SQ6162.fastq.gz?response-content-disposition=attachment; filename=FF05466731.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=KSBXBGuNyh7r1Yk2cReXArA71wc%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_754a75337a1049f8/SQ6159.fastq.gz?response-content-disposition=attachment; filename=FF05466092.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=zZhREWjUUSH8IWF2mv5ErGfv%2BMk%3D

