#PBS -N download_fitness_7
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_95735784138f414e/SQ6955.fastq.gz?filename=FF05466551.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Vj4AslRNx873pV5EnniPPnr5NqE%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_4aaa34ce23614f30/SQ6989.fastq.gz?filename=FF05466735.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=x6HHTRT5EHooMo5Kk5B2VwGTJgo%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_928cadecb6904e9c/SQ6969.fastq.gz?filename=FF05466581.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=UxUL%2BeaCrP15ZkQCESnzXEtKsj0%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_70a31a11b7f04b95/SQ6974.fastq.gz?filename=FF05466194.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=YPHyFmYPiC1DqLeqVHCBUZQp5VY%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_de445d96be7046db/SQ6963.fastq.gz?filename=FF05466127.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=hPaF9bjSjEf5jCh1HRv2XhyzslQ%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_82d9a655d1b94856/SQ6990.fastq.gz?filename=FF05466307.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=glHccSEA2raslKi62V4%2BgMPpJ9s%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_424f6175645b4ee6/SQ6171.fastq.gz?filename=FF05466346.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=vB4yh%2BesHvM3W67JxvjEL0CaP8c%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_e2d1be0d8a8c40eb/SQ6973.fastq.gz?filename=FF05464140.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=yvLqA%2B8kG5KMg7PpRFLBbnzhc%2Fg%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_df82cd8c5b554ebc/SQ6938.fastq.gz?filename=FF05466767.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=tiabPEOe9njBdT5RXnQ3R5%2FUwnM%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_7f4254aa346145e5/SQ6956.fastq.gz?filename=FF05466627.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=UhdoraU3Wr4r9UeBavqtQzk2IM0%3D

