#PBS -N download_fitness_5
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_9f7b9358d2b34e83/SQ6909.fastq.gz?filename=FF05466072.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=tFPHPCSIHZ5XnHbWV7y7uf9AlfE%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_229a7bb6bdde4748/SQ6169.fastq.gz?filename=FF05466387.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Tur3CV8a1kBo2%2B5SWKe6o3yBcTY%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_53140159746a47d8/SQ6168.fastq.gz?filename=FF05466597.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=0xtEd4HoAOehsR%2BRA75P5PkD58s%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_aedb3f899ab54a15/SQ6931.fastq.gz?filename=FF05464407.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Q5aVwzZ2N3Lz4P8pC%2FckBxKygrc%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_1f4b5bc16edd4fd1/SQ6916.fastq.gz?filename=FF05465961.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=xPaGcNnegRETRc%2FRxVnVQVfsEhE%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_1c3d2cb87cf4488a/SQ6918.fastq.gz?filename=FF05466562.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=oxGYgPUfLaZDTV4JXMOP2kL%2FDU8%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_6dd7fed25abf456c/SQ6920.fastq.gz?filename=FF05466584.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=w4im6HVlfLntnDj7kCLR8GpDiz4%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_e1bade602f0f4a56/SQ6934.fastq.gz?filename=FF05466077.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=g7Xu9cqJUKim5Ani8iscxIQ4Rcw%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_251bb794cc1441a0/SQ6941.fastq.gz?filename=FF05466001.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=SdnSPvZb75ex1ZwUW4ccmgF92%2FM%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_96d309f7daa34852/SQ6940.fastq.gz?filename=FF05464542.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=NvYQQQ8ShRCJarCkMYx7AxvO95w%3D

