#PBS -N download_fitness_3
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_094011be86ed4c66/SQ6964.fastq.gz?response-content-disposition=attachment; filename=FF05466328.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=dsaTFRLz6%2BmD6FBJyxbcw3M7kmQ%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_1a0fc045eb7444bd/SQ6981.fastq.gz?response-content-disposition=attachment; filename=FF05466734.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=vtayOf%2Bt9DBz34vH9AFEeDtdSWI%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_de2dab0ea0e849bd/SQ6962.fastq.gz?response-content-disposition=attachment; filename=FF05465966.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=OUSm7HmsO%2B2BziUGhuA1PR6G1Z4%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_ce19596c185d42ed/SQ6980.fastq.gz?response-content-disposition=attachment; filename=FF05466582.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=PaF%2BDQ7ZTEwG7KEuM%2BYbLu%2FGLjE%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_3e2f19731bb44043/SQ6953.fastq.gz?response-content-disposition=attachment; filename=FF05464197.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Boj3%2BpTm4kj1PqZot9J%2BEujSHvk%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_37991517fcbb4391/SQ6983.fastq.gz?response-content-disposition=attachment; filename=FF05466753.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=gafI5SHsNWNA1iFxpFYKi8dArKs%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_2315dac147164bd5/SQ6977.fastq.gz?response-content-disposition=attachment; filename=FF05466095.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=Z6nbRT%2B8uUypvJaxdSpHDPhcNIU%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_99b576966241422a/SQ6968.fastq.gz?response-content-disposition=attachment; filename=FF05466332.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=MQEEXyksTq4FOzo335gFtD53Img%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_bbe722f8698a4c27/SQ6937.fastq.gz?response-content-disposition=attachment; filename=FF05466606.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=BmnyUk4AqZdocvFPl6oSR5jb7rU%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_88780e10f89f443e/SQ6975.fastq.gz?response-content-disposition=attachment; filename=FF05466384.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=t%2BYKmMsvZNoSkDNt%2Fdaymlf0zZE%3D

