#PBS -N download_fitness_11
#PBS -A PAS1695
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe

cd /fs/ess/PAS1695/projects/fitness/data/fastqs/
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_a80cea5e8c90425a/SQ6967.fastq.gz?filename=FF05466619.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=nFvT0GFQVizo4TF9RqTC21unsbI%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_39ed99dab49644b4/SQ6988.fastq.gz?filename=FF05465964.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=5oA6AebfBa%2BeKbgbMuv9YmJiTuI%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_372d9a03f9804e81/SQ6908.fastq.gz?filename=FF05466147.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=MTISUTxYV1sfJFEk6%2Fc8AbYJ5iU%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_e05c25b525e24efd/SQ6930.fastq.gz?filename=FF05466151.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=SvBCR62zX0jrFYKcKNV1sUNLW7Y%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_1a1944969efb4b09/SQ6165.fastq.gz?filename=FF05466292.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=y%2FaopFXAcatvJ16ts2wApKGNy30%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_fbc0f8ae24654d4d/SQ6156.fastq.gz?filename=FF05466564.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=kqbqsCeL9GMH3kLflYGJGs18PIs%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_01f49c78f46c49fd/SQ6152.fastq.gz?filename=FF05466548.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=P%2BfBb6fwhjdyXDupBbeyvKIP9II%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_2232a67ed0fd47dd/SQ6987.fastq.gz?filename=FF05464304.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=UafBCe77h6f66hVjlXIRdBmWUjY%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_9ce32414e3954380/SQ6163.fastq.gz?filename=FF05466313.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=8%2BPP%2BInSl02vO3b2rMha7wvLd0E%3D
wget https://s3.amazonaws.com/refgenomics-userdata-production-encrypted/user_296ad2f563604ef1/file_dfe97713dd284d2b/SQ6161.fastq.gz?filename=FF05466380.fastq.gz&AWSAccessKeyId=AKIA6GPUEB7CLCIK2XEI&Expires=1625594771&Signature=3ocYHhPRijKruZNsVjyOjx5as%2BM%3D

