---
title: "ASCO 2021"
author: "Rebecca Hoyd"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tableone)
library(vegan)
library(rlist)
library(broom)
```

# Load data
```{r}
asco.dir <- "T:/Labs/Spakowicz/projects/fitness/ASCO2021"

clin <- read.csv(file.path(asco.dir, "clinical-with-seqids_baseline.csv"), stringsAsFactors = F)
ra.table <- read.csv(file.path(asco.dir, "matched-microbes_baseline.csv"), stringsAsFactors = F)

```

# Table 1

```{r}
# Try restricting to species
s.alphadiv <- ra.table %>%
  select(contains("s__")) 
diversity(s.alphadiv, index = "shannon")
# Try for genus
g.alphadiv <- ra.table %>%
  select(contains("g__")) %>%
  select(-contains("s__"))
diversity(g.alphadiv, "shannon")
# Still NAs, mocving on for now

tab1in <- clin %>%
  mutate(Age = age_cat,
         Race = race,
         Sex = sex,
         `Cancer Type` = lung_cancer_type,
         Stage = cancer_stage_collap,
         Treatment = first_planned_regimen,
         CARG = carg_score,
         SPPB = sppb_score,
         `FS 7` = fs_7_score,
         `FS 13` = fs_13_score,
         `Time up and go` = tug,
         PROMIS = promis_score,
         BLESSED = blessed_score)

listVars <- c("Age", "Sex", "Race", "Cancer Type", "Stage", "Treatment", "CARG", "SPPB", "FS 7", "FS 13", "PROMIS",
              "BLESSED", "Time up and go")
catVars <- c("Sex", "Race", "Cancer Type", "Stage", "Treatment")
table1 <- CreateTableOne(vars = listVars,
                         data = tab1in,
                         factorVars = catVars)

table1
```

# Modeling

## Which vars to try?
We'll go for CARG and FS 13 for now. 
```{r}
hist(tab1in$CARG)
hist(tab1in$`FS 13`)
hist(tab1in$SPPB)

```
## Shared formatting

```{r}
modin <- clin %>%
  left_join(ra.table) %>%
  mutate(bin.fs13 = ifelse(fs_13_score == 1, 0, 1))

mics <- colnames(ra.table[,-1])
```

```{r}
capture.models.univ <- function(outcome, lfun){
  mods.list <- lapply(mics, function(x) try({glm(as.formula(paste0(outcome, " ~ ", x)), family = lfun, data = modin) %>%
                        tidy()})
                      )
                      
  mods.list.clean <- list.clean(mods.list, function(x) is.null(x))
  mods.df <- bind_rows(mods.list.clean)
  return(mods.df)
}
```

## CARG

```{r}
carg.mods <- capture.models.univ("carg_score", "gaussian") %>%
  filter(term != "(Intercept)") %>%
  arrange(p.value)

head(carg.mods)
```

## FS 13

```{r}
fs13.mods <- capture.models.univ("bin.fs13", "binomial") %>%
  filter(term != "(Intercept)") %>%
  arrange(p.value)

head(fs13.mods)
```