---
title: "baseline sample matching"
author: "Rebecca Hoyd"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readxl)
library(tidyr)
source("00-paths.R")
```

# Load data

```{r}
idkeys <- lapply(1:2, function(x) read_excel(path = file.path(paths$controlled, "OSU-18055 shared patient log.xlsx"),
                                             sheet = x))
patkey.raw <- read_excel(file.path(paths$data, "key_sequence-to-date.xlsx"))
cycle.key = read_excel(file.path(paths$data, "fitness.cycles.xlsx"))

runcheck <- read_excel(file.path(paths$data, "Fitness-samples-tbr-2021.xlsx"))

batch1 <- read.csv(file.path(paths$t.drive, "data", "aggtab_metaphlan_QC-filtered.csv"), stringsAsFactors = F)
batch2 <- read.csv(file.path(paths$t.drive, "data", "20025_metaphlan_filtered.csv"), stringsAsFactors = F)

clindat <- read.csv(file.path(paths$data, "Fitness_dataset.csv"), stringsAsFactors = F)
```

# Key formatting
```{r}
idkeys.keyon <- lapply(idkeys, function(x) x[, 1:2])
idkeys.form <- bind_rows(idkeys.keyon) %>%
  gather(-`study ID`, key = "sheet", value = "id") %>%
  rename("patient.id" = "study ID") %>%
  filter(!is.na(id))
```

```{r}
patkey <- patkey.raw %>%
  filter(!is.na(Order)) %>%
  rename('sequence.id' = "Code") %>%
  separate(Name, sep = " ", into = c("patient.id", "date")) %>%
  mutate(year = paste0(20, substr(date, 1, 2)),
         month = substr(date, 3, 4),
         day = substr(date, 5,6),
         date = as.POSIXct(paste(year, month, day, sep = "/"), format = "%Y/%m/%d"),
         patient.id = as.numeric(patient.id)) %>%
  select(sequence.id, patient.id, date) %>%
  mutate(date = as.character(date))

cycle.key <- cycle.key %>%
  rename("patient.id" = "Patient id",
         "date" = "Sample date",
         "cycle" = "Cycle #") %>%
  mutate(date = as.character(date))

patcy <- patkey %>%
  filter(patient.id > 1000) %>%
  left_join(cycle.key)
```

# Get good samples

```{r}
length(unique(patcy$patient.id))

goodsamps <- intersect(full.microbes$Sample.Code, patkey$sequence.id)

earliest.samps <- patcy %>%
  filter(sequence.id %in% goodsamps) %>%
  group_by(patient.id) %>%
  filter(date == min(date) | is.na(date)) %>%
  left_join(idkeys.form) %>%
  select(-sheet, -date) 

full.microbes <- bind_rows(batch1, batch2)


```

```{r}
clindat.sampkey <- clindat %>%
  inner_join(earliest.samps)

matched.microbes <- full.microbes %>%
  filter(Sample.Code %in% clindat.sampkey$sequence.id) %>%
  rename("sequence.id" = "Sample.Code")
```

# Write results

```{r}
write.csv(clindat.sampkey, file.path(paths$t.drive, "data", "clinical-with-seqids_baseline.csv"), row.names = F)
write.csv(matched.microbes, file.path(paths$t.drive, "data", "matched-microbes_baseline.csv"), row.names = F)
```

