---
title: "baseline sample matching"
author: "Rebecca Hoyd"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readxl)
library(tidyr)
source("00-paths.R")
```

# Load data

```{r}
idkeys.SpakPres <- lapply(1:2, function(x) read_excel(path = file.path(paths$controlled, 
                                                                       "OSU-18055 shared patient log.xlsx"),
                                             sheet = x))

idkeys.SpakOne <- read.csv(file.path(paths$t.drive, "data", "onecodex", "One Codex Sample Sheet.csv"),
                           stringsAsFactors = F) %>%
  select(Name, External.Sample.ID)

OCbatch <- read.table("../data/OneCodex_merged_output.txt", stringsAsFactors = F, header = T)

clindat <- read.csv(file.path(paths$data, "Fitness_dataset.csv"), stringsAsFactors = F)
```

# Key formatting
```{r}
idkeys.keyon <- lapply(idkeys.SpakPres, function(x) x[, 1:2])
idkeys.form <- bind_rows(idkeys.keyon) %>%
  gather(-`study ID`, key = "sheet", value = "id") %>%
  rename("patient.id" = "study ID") %>%
  filter(!is.na(id))

patkey <- idkeys.SpakOne %>%
  # filter(!is.na(Order)) %>%
  rename('sequence.id' = "External.Sample.ID",
         "Sample" = "Name") %>%
  separate(Sample, sep = "\\.", into = c("patient.id", "Sample")) %>%
  mutate(year = paste0(20, substr(Sample, 1, 2)),
         month = substr(Sample, 3, 4),
         day = substr(Sample, 5,6),
         date = as.POSIXct(paste(year, month, day, sep = "/"), format = "%Y/%m/%d"),
         patient.id = as.numeric(patient.id)) %>%
  select(sequence.id, patient.id, date) %>%
  mutate(stool_sample_date = as.character(date))
```

# Get good samples

```{r}
length(unique(patkey$patient.id))

goodsamps <- intersect(colnames(OCbatch), patkey$sequence.id)

earliest.samps <- patkey %>%
  filter(sequence.id %in% goodsamps) %>%
  group_by(patient.id) %>%
  filter(date == min(date) | is.na(date)) %>%
  left_join(idkeys.form) %>%
  select(-sheet, -date) 


```

```{r}
clindat.sampkey <- clindat %>%
  inner_join(earliest.samps) %>%
  select(-stool_sample_date)

matched.microbes <- OCbatch %>%
  dplyr::select(-NCBI_tax_id) %>%
  gather(-clade_name, key = "sequence.id", value = "relative.abundance") %>% 
  filter(sequence.id %in% clindat.sampkey$sequence.id)
```

# Write results

```{r}
write.csv(clindat.sampkey, file.path(paths$t.drive, "data", "clinical-with-seqids_baseline_OneCodex.csv"), row.names = F)
write.csv(matched.microbes, file.path(paths$t.drive, "data", "matched-microbes_baseline_OneCodex.csv"), row.names = F)
```

