---
title: "CARG + microbe"
author: "Caroline Wheeler"
date: "2023-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(randomForest)
library(ggplot2)
library(ROCR)
library(gdata)
library(ggpubr)
library(vegan)
```

load data - note from 2 dif T-drives
```{r}
# PC path
# data.dir <- "T:/Labs/Spakowicz/fitness/data/derived"
# mac path 
data.dir <- "/Volumes/spakowicz/fitness/data/derived"

clin <- read.csv(file.path(data.dir, "clinical-with-seqids_baseline_OneCodex.csv"), stringsAsFactors = F)
tax <- read.csv(file.path(data.dir, "matched-microbes_baseline_OneCodex.csv"), stringsAsFactors = F) %>%
  spread(key = clade_name, value = relative.abundance)

tox <- read.csv("/Volumes/presley/FITNESS-lung/Microbiome- Rebecca/CoRR5512FITNESSCalcu_DATA_2022-10-04_1152.csv")
```

simplify microbe column names
```{r}
tax.names <- sub(".*\\|", "", colnames(tax))
colnames(tax) <- tax.names
```

some clin data clean up 
```{r}
idkey <- tox %>%
    select(id, sid_2) %>%
    drop_na()

toxnest <- tox %>%
  filter(redcap_repeat_instrument == "adverse_events_and_toxicities_new" &
           grepl("arm_2", redcap_event_name)) %>%
  select(id, tox_grade_new, redcap_event_name) %>%
  drop_na(tox_grade_new) %>%
  group_by(id, redcap_event_name) %>%
  summarise(max.gade = max(tox_grade_new)) %>%
  # mutate(tox_onset_new2 = as.character(tox_onset_new2)) %>%
  left_join(idkey) %>%
  mutate(patient.id = as.character(sid_2))

tox.maxgrade <- toxnest %>%
  group_by(id, patient.id) %>%
  summarise(maxgrade = max(max.gade)) %>%
  mutate(high.tox = ifelse(maxgrade >= 3, 1,0))

# grab patient ID's and sequnce ID's - 32 total 
clin <- clin %>%
  select(id, sequence.id, patient.id)

baseline.vals <- tox %>% 
  filter(!is.na(carg_score) & grepl("arm_2", redcap_event_name)) %>%
  select(id, contains("carg")) %>%
  select(-contains("complete"), -contains("timestamp"))

baseline.vals <- baseline.vals %>%
  left_join(tox.maxgrade) %>%
  select(id, patient.id, carg_score, maxgrade, high.tox) %>%
  mutate(patient.id = as.integer(patient.id))

# join with RNAseq keeping only 32 pts with microbe samples
clin <- left_join(clin, baseline.vals) %>%
  select(sequence.id, carg_score, high.tox)
```

ensure that clin and mic data line up
```{r}
temp <- merge(clin, tax) %>%
  filter(!is.na(carg_score))

# tax + carg
tax.carg <- temp %>%
  select(-high.tox)

# carg alone
carg <- temp %>%
  select(sequence.id, carg_score)

# var to predict
high.tox <- temp %>%
  select(sequence.id, high.tox)

# check that the orders match
identical(tax.carg$sequence.id, high.tox$sequence.id)
```

<!-- calculate diversity measures  -->
<!-- ```{r} -->
<!-- div <- ra %>%  -->
<!--   group_by(sample) %>% -->
<!--   summarize(sobs = specnumber(exo.ra), -->
<!--             shannon = diversity(exo.ra, index = "shannon"), -->
<!--             simpson = diversity(exo.ra, index = "simpson"), -->
<!--             invsimpson = 1/simpson) %>% -->
<!--   mutate(chao = as.data.frame(t(estimateR(counts)))$S.chao1, -->
<!--          ACE = as.data.frame(t(estimateR(counts)))$S.ACE) -->


<!-- div <- temp %>% -->
<!--   select(-high.tox, -carg_score) %>% -->

<!-- ``` -->


######## Function to make the model and predictions ######
```{r}
getROC <- function(train, clin.train, test, clin.test){
  model.training <- randomForest(x = train[,-1, drop=FALSE], y = as.factor(clin.train$high.tox))
  test.preds <- predict(model.training, test[,-1, drop=FALSE])
  
  print(model.training)
  # Check variable importance
  varImpPlot(model.training)
  # Prediction confusion matrix
  table(observed = clin.test$high.tox, predicted = test.preds)
  
  prediction_for_roc_curve <- predict(model.training,test[,-1, drop=FALSE],type="prob")
  pred <- prediction(prediction_for_roc_curve[,2], clin.test$high.tox)
  perf <- performance(pred, "tpr", "fpr")
  
  auc_ROCR <- performance(pred, measure = "auc")
  print(auc_ROCR)
  auc <- auc_ROCR@y.values[[1]]
  print(auc)
  
  df <- data.frame(FalsePositive=c(perf@x.values[[1]]),
                    TruePositive=c(perf@y.values[[1]]))
  
  return(df)
}
```

Split into testing and training data
```{r}
testn <- round(.33 * nrow(high.tox))
set.seed(30)
testsamps <- sample(high.tox$sequence.id, testn)

# exo with microbes
train.tax <- tax.carg %>%
  dplyr::filter(!sequence.id%in% testsamps)
test.tax <- tax.carg %>%
  dplyr::filter(sequence.id %in% testsamps)

train.carg <- carg %>%
  dplyr::filter(!sequence.id%in% testsamps)
test.carg <- carg %>%
  dplyr::filter(sequence.id %in% testsamps)

# all clin vars
clin.train <- high.tox %>%
  dplyr::filter(!sequence.id %in% testsamps)
clin.test <- high.tox %>%
  dplyr::filter(sequence.id %in% testsamps)
```

```{r}
carg_AUC <- getROC(train.carg, clin.train, test.carg, clin.test)
tax.carg_AUC <- getROC(train.tax, clin.train, test.tax, clin.test)
```
## plot ROC
```{r}
carg_plot <- ggplot(carg_AUC , aes(x=FalsePositive, y=TruePositive)) + 
  theme_bw() +
  geom_smooth(se = FALSE, color="darkgreen") +
    xlab("Specifity") +
  ylab("Sensitivity") +
  annotate(geom="text", x=0.8, y=0.7, label="AUC = 0.875",
              color="darkgreen", size=8) 

carg_plot

tax.carg_AUC_plot <- ggplot(tax.carg_AUC, aes(x=FalsePositive, y=TruePositive)) + 
  theme_bw() +
  geom_smooth(se = FALSE, color="cornflowerblue") +
    xlab("Specifity") +
  ylab("Sensitivity") +
  annotate(geom="text", x=0.8, y=0.5, label="AUC = 0.5",
              color="cornflowerblue", size=8) 

tax.carg_AUC_plot
```
combined plot
```{r}
temp <- combine(carg_AUC, tax.carg_AUC)

combined <- ggplot(temp, aes(x=FalsePositive, y=TruePositive, color=source)) + 
  theme_bw() +
  geom_smooth(se = FALSE) +
  scale_color_manual(values=c("cornflowerblue", "deeppink4")) +
  xlab("Specifity") +
  ylab("Sensitivity") +
  annotate(geom="text", x=0.8, y=0.5, label="AUC = 0.875",
              color="cornflowerblue", size=8) + 
  annotate(geom="text", x=0.8, y=0.4, label="AUC = 0.5",
              color="deeppink4", size=8)

combined
```

