---
title: "diversity_tx-response"
author: "Dan Spakowicz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

Is diversity associated with tx response in the FITNESS cohort?

```{r}
div <- read_csv("../data/OC_simpson-diversity.csv") %>%
  mutate(patient.id = as.character(patient.id))

head(div)
```

```{r}
response <- readRDS("../data/timeline_stool-patient-only.RDS")$recist

tx <- readRDS("../data/timeline_stool-patient-only.RDS")$ribbon 
```

```{r}
comb <- full_join(div, response) %>%
  full_join(tx) %>%
  drop_na(RECIST_month3)
```

```{r}
comb %>%
  ggplot(aes(x = RECIST_month3, y = Simpson.div)) +
  geom_boxplot()
```
Filter to just the baseline samples, one per person. 

```{r}
comb %>%
  mutate(visit.num = gsub(".*_visit_(\\d+)_arm_2", "\\1", redcap_event_name)) %>%
  group_by(patient.id) %>%
  filter(visit.num == min(visit.num)) %>%
  arrange(patient.id) %>%
    ggplot(aes(x = RECIST_month3, y = Simpson.div)) +
  geom_boxplot(aes(fill = RECIST_month3), show.legend = FALSE) +
  geom_jitter() +
  theme_bw() 
  
```
Ensure these patients receive IO. 

```{r}
comb %>%
  filter(grepl("io", summarise_treatment)) %>%
      ggplot(aes(x = RECIST_month3, y = Simpson.div)) +
  geom_boxplot()
```

