---
title: "Survival tests"
output: html_document
date: "2023-08-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(survival)
library(survminer)
```


# Load data

```{r}
clin.withdate <- read.csv(paste0(paths$controlled, "/CoRR5512FITNESSCalcu_DATA_2022-10-04_1152.csv"), stringsAsFactors = F)
colnames(clin.withdate)[1] <- "id"
```

# Formatting

```{r}
idkey <- clin.withdate %>%
    select(id, sid_2) %>%
    drop_na()
```

```{r extract survival data}
survdat <- clin.withdate %>%
  # filter(redcap_repeat_instrument=="") %>%
  select(id, redcap_event_name,
         enrollment_date, life_status,
         date_of_death, last_followup) %>%
  drop_na(life_status) %>%
  filter(enrollment_date != "" & grepl("arm_2", redcap_event_name)) %>%
  # Mutate block for collecting dates
  mutate(date_of_death = ifelse(date_of_death == "", NA, date_of_death),
         last_followup = ifelse(last_followup == "", NA, last_followup),
         enddat = coalesce(date_of_death, last_followup),
         enddat = ifelse(life_status == 1, date_of_death, enddat),
         enddat = ifelse(life_status ==0 & is.na(last_followup), 
                         "2022-10-04", 
                         enddat)) %>%
  # Mutate block for formatting to days
  mutate(enddat = as.Date(enddat),
         enrollment_date = as.Date(enrollment_date),
         days = as.numeric(enddat - enrollment_date)) %>%
  select(id, life_status, days) %>%
    drop_na(days)

survdat.man <- as.data.frame(cbind(id = c(138,200,209,211,212,214, 165),
                                   enddat = c("2022-12-14", "2021-09-14",
                                              "2023-06-14", "2023-06-21",
                                              "2023-08-04", "2021-10-27",
                                              "2023-06-12"),
                                   life_status = c(1,1,0,0,0,0,0)),
                             stringsAsFactors = F) %>%
  mutate(id = as.numeric(id),
         life_status = as.numeric(life_status))

survdat.man.form <- clin.withdate %>%
  select(id, enrollment_date) %>%
  filter(enrollment_date != "") %>%
  right_join(survdat.man) %>%
  mutate(enddat = as.Date(enddat),
         enrollment_date = as.Date(enrollment_date),
         days = as.numeric(enddat - enrollment_date)) %>%
  select(id, life_status, days) 

survdat.form <- bind_rows(survdat, survdat.man.form)
```

```{r}
# test <- clin.withdate %>%
#   select(id,enrollment_date, redcap_event_name, life_status, date_of_death, last_followup) %>%
#   drop_na(life_status) %>%
#   filter(enrollment_date != "" & grepl("arm_2", redcap_event_name)) %>%
#   # Mutate block for collecting dates
#   mutate(date_of_death = ifelse(date_of_death == "", NA, date_of_death),
#          last_followup = ifelse(last_followup == "", NA, last_followup),
#          date_of_death = as.Date(date_of_death),
#          last_followup = as.Date(last_followup)) %>%
#   filter(!is.na(date_of_death) & !is.na(last_followup)) %>%
#   mutate(early_death = date_of_death < last_followup)
# 
# test %>%
#   select(id, early_death)

arm2pats <- clin.withdate %>%
  filter(grepl("arm_2", redcap_event_name))
arm2pats <- unique(arm2pats$id)
test <- clin.withdate %>%
  group_by(id) %>%
  summarise(any(!is.na(life_status))) %>%
  filter(id %in% arm2pats)

clin.withdate %>%
  filter(redcap_repeat_instrument=="") %>%
  select(id, redcap_event_name,
         enrollment_date, life_status,
         date_of_death, last_followup) %>%
  # drop_na(life_status) %>%
  filter(enrollment_date != "" & grepl("arm_2", redcap_event_name)) %>%
  # Mutate block for collecting dates
  mutate(date_of_death = ifelse(date_of_death == "", NA, date_of_death),
         last_followup = ifelse(last_followup == "", NA, last_followup),
         enddat = coalesce(date_of_death, last_followup),
         enddat = ifelse(life_status == 1, date_of_death, enddat),
         enddat = ifelse(life_status ==0 & is.na(last_followup), 
                         "2022-10-04", 
                         enddat)) %>%
  # Mutate block for formatting to days
  mutate(enddat = as.Date(enddat),
         enrollment_date = as.Date(enrollment_date),
         days = as.numeric(enddat - enrollment_date)) %>%
  filter(is.na(life_status)) %>%
  select(id, life_status)
```

```{r extract other variables}
clinvars <- clin.withdate %>%
  select(id, carg_score) %>%
  drop_na() %>%
  mutate(carg_high = ifelse(carg_score >=8 ,1, 0))
```

```{r final data object}
modin.surv <- survdat.form %>%
  left_join(clinvars) %>%
  drop_na(carg_high)
```

# Modelling

## CARG >= 8
```{r}
carg.res <- surv_fit(Surv(days, life_status) ~ carg_high, data = modin.surv)

cargplot <- ggsurvplot(carg.res, pval = T, risk.table = T, palette = c("black", "red"))
```

```{r}
png("../figures/survival-curve_CARG-ge8.png")
cargplot
dev.off()
```

