---
title: "PCA response"
output: html_document
date: '2022-10-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Load data

```{r}
mettab <- read.table("T:/Labs/Spakowicz/fitness/data/derived/merged_metaphlan_output.txt",
                     header = T, sep = "\t")
recist <- read.csv("../data/RECIST.csv", stringsAsFactors = F)
key <- read.csv("T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/key_fitness-microbe-clin.csv",
                stringsAsFactors = F)
```

# Format

```{r}
formatRunPCA <- function(){
  tmp.meta <- key %>%
    mutate(patient.id = as.character(patient.id)) %>%
    left_join(recist) %>%
    mutate(r.nr = case_when(RECIST_month3 %in% c("CR", "PR") ~ "R",
                            RECIST_month3 %in% c("PD", "SD") ~ "NR"))
  
  tmp.matrix <- mettab %>%
    select(-NCBI_tax_id) %>%
    filter(grepl("s__", clade_name)) %>%
    column_to_rownames(var = "clade_name") %>%
    t()
  
  pca.res <- prcomp(tmp.matrix, scale. = T)  

  plotin <- pca.res$x %>%
    as.data.frame() %>%
    rownames_to_column(var = "sequence.id") %>%
    select(sequence.id, PC1, PC2) %>%
    left_join(tmp.meta) %>%
    drop_na(patient.id)
}

```

# Plot

```{r}
pca.res <- formatRunPCA()

pca.res %>%
  ggplot(aes(x = PC1, y = PC2, fill = RECIST_month3, color = RECIST_month3)) +
  stat_ellipse(geom = "polygon", alpha = .5, type = "norm") +
  geom_point() +
  theme_bw()
ggsave("../figures/pca_recist_cats.png")

pca.res %>%
  drop_na(r.nr) %>%
  ggplot(aes(x = PC1, y = PC2, fill = r.nr, color = r.nr)) +
  stat_ellipse(geom = "polygon", alpha = .5, type = "norm") +
  geom_point() +
  theme_bw()
ggsave("../figures/pca_recist_R-NR.png")
```