---
title: "Concomitant PPI"
author: "Rebecca Hoyd"
date: "7/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis)
library(readxl)
library(stringr)
source("00-paths.R")
```


# Load data

```{r}
# corr <- read.csv("../data/CoRR_concomitent-meds.csv", stringsAsFactors = F)
# colnames(corr)[1] <- "id"
# 
# ppi <- read.table("T:/Labs/Spakowicz/ppiio/data/curated/proton-pump-inhibitors.txt", 
#                   stringsAsFactors = F, sep = "\t") %>%
#     rename("medname" = "V1") %>%
#     mutate(medclass = "PPI")

ICI.meds.raw <- read_excel("../data/FITNESS_TreatmentCategories_8.23.21.xlsx")

clin <- read.csv(file.path(paths$t.drive, "data", "clinical-OC-matched_resolved_limited.csv"), stringsAsFactors = F)
clin.withdate <- read.csv(file.path(paths$controlled, "clinical-OC-matched_resolved.csv"), stringsAsFactors = F)

studcy <- read_excel("../data/cycle_study-visit-tracker_v3.xlsx")
```

# Functions

```{r}
# determine_ppis <- function(mednames, allmeds){
#   meds.members <- lapply(mednames, function(x) as.data.frame(cbind(
#     allmeds = unique(allmeds[grepl(x,
#                                         allmeds,
#                                         ignore.case = T)]),
#     medname = x))) %>%
#     bind_rows() %>%
#     mutate(allmeds = as.character(allmeds),
#            medname = as.character(medname),
#            medclass = "ppi")
#   
#   return(meds.members)
# }
  
```

# Defining ppi y/n

## Data manipulations

```{r}
# corr.l <- corr %>%
#   select("id", "redcap_event_name", contains("agent")) %>%
#   gather(contains("agent"), key = "mednumber", value = "allmeds") %>%
#   filter(!is.na(allmeds) & allmeds != "")
# 
# alagents <- unique(corr.l$allmeds)
# ppis.in.set <- determine_ppis(ppi$medname, alagents)
# 
# 
# corr.ppilab <- corr.l %>%
#   left_join(ppis.in.set) %>%
#   mutate(ppi = ifelse(is.na(medclass), 0, 1))
# 
# corr.ppi.summarize <- corr.ppilab %>%
#   group_by(id, redcap_event_name) %>%
#   summarise(ppi = sum(ppi)) %>%
#   mutate(ppi = ifelse(ppi >= 1, 1, 0))
```

## Save

```{r}
# write.csv(corr.ppi.summarize, file.path(paths$t.drive, "data", "patient_concommitant_ppis_2.csv"), row.names = F)

# corr.ppi.summarize <- read.csv(file.path(paths$t.drive, "data", "patient_concommitant_ppis_2.csv"))

corr.ppi.summarize <- read.csv("T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/S2345FITNESSSConcomi_DATA_2022-03-07_1522.csv", stringsAsFactors = F) %>%
  mutate(patient.id = record_id,
         ppi = ppis) %>%
  select(patient.id, ppi)
```

# Visualize timelines


## Get treatment groups

```{r}
ICI.meds <- ICI.meds.raw %>%
  rename(ici.nums = ...1,
         ici.name = `Category (chemo, chemo + io, io, targeted, targeted+chemo)`) %>%
  mutate(ici.name =str_replace_all(ici.name, "\\s", ""))
```

```{r}
# test <- colnames(clin)
# test[grep("the", test)]
# sort(test)

clin.filt <- clin %>%
  select("patient.id", "sequence.id", "redcap_event_name", contains("tx_reg"))

studcy.l <- studcy %>%
  gather(-`Patient ID`, key = "study.vis", value = "cycle") %>%
  mutate(patient.id = `Patient ID`) %>%
  filter(grepl("cycle", cycle)) %>%
  mutate(redcap_event_name = paste0("study_visit_", gsub("Study Visit ", "", study.vis), "_arm_2")) %>%
  separate(cycle, into = c("hold", "cycle")) %>%
  select(patient.id, redcap_event_name, cycle)

clin.timein <- clin.filt %>%
  mutate(ici.nums = as.character(ifelse(!is.na(tx_reg_1_2), tx_reg_1_2, tx_reg_1))) %>%
  select(patient.id, sequence.id, redcap_event_name, ici.nums) %>%
  drop_na(ici.nums) %>%
  mutate(ici.nums = as.numeric(ici.nums)) %>%
  left_join(ICI.meds) %>%
  left_join(corr.ppi.summarize) %>%
  left_join(studcy.l) %>%
  mutate(ppi = ifelse(is.na(ppi), 0, ppi),
         ici.name = ifelse(is.na(ici.name), "Not.ICI", ici.name),
         visit.type = gsub("(^\\w+)_visit.*", "\\1", redcap_event_name),
         tpoint = ifelse(visit.type == "cycle",
                         gsub(".*_visit_(\\d).*", "\\1", redcap_event_name),
                         cycle),
         # ppi = ifelse(visit.type == "cycle", "Unknown", ppi),
         tpoint.2 = str_pad(tpoint, width = 2, side = "left", pad = "0"))
  # filter(grepl("study", redcap_event_name))
```

```{r}
ggplot(clin.timein, aes(x = tpoint.2, y = as.factor(patient.id), shape = as.factor(ppi), color = ici.name, alpha = visit.type)) +
  geom_point(size = 3) +
  labs(y = "Patient", x = "Cycle") +
  scale_color_viridis_d(name = "Treatment", option = "turbo") +
  scale_shape(name = "PPI") +
  scale_alpha_manual(breaks = c("cycle", "study"), values = c(.4, 1), guide = FALSE) +
  theme_bw() 
ggsave("../figures/timeline_sample-points_treatment-ppi.png", height = 5, width = 5)
```

# Make a version where x=days

```{r}
clin.filt.days <- clin.withdate %>%
  select("patient.id", "sequence.id", "redcap_event_name", "stool_sample_date", contains("tx_reg")) %>%
  group_by(patient.id) %>%
  mutate(stool_sample_date = as.Date(stool_sample_date),
         earliest_day = min(stool_sample_date),
         elapsed.days = as.numeric(stool_sample_date - earliest_day)) %>%
  ungroup() %>%
  select("patient.id", "sequence.id", "redcap_event_name", "stool_sample_date", "earliest_day", "elapsed.days", contains("tx_reg"))

clin.timein.days <- clin.filt.days %>%
  mutate(ici.nums = as.character(ifelse(!is.na(tx_reg_1_2), tx_reg_1_2, tx_reg_1))) %>%
  select(patient.id, sequence.id, redcap_event_name, elapsed.days, ici.nums) %>%
  drop_na(ici.nums) %>%
  mutate(ici.nums = as.numeric(ici.nums)) %>%
  left_join(ICI.meds) %>%
  left_join(corr.ppi.summarize) %>%
  left_join(studcy.l) %>%
  mutate(ppi = ifelse(is.na(ppi), 0, ppi),
         ici.name = ifelse(is.na(ici.name), "Not.ICI", ici.name),
         visit.type = gsub("(^\\w+)_visit.*", "\\1", redcap_event_name),
         tpoint = as.numeric(ifelse(visit.type == "cycle",
                         gsub("cycle_visit_(.*)_arm.*", "\\1", redcap_event_name),
                         cycle))
         # ppi = ifelse(visit.type == "cycle", "Unknown", ppi),
         ) %>%
  group_by(patient.id) %>%
  mutate(minimun_cycle = min(tpoint),
         ylabs = paste0(patient.id, "(", minimun_cycle, ")")) %>%
  ungroup()
```

```{r}
ggplot(clin.timein.days, aes(x = elapsed.days, y = as.factor(ylabs), shape = as.factor(ppi), color = ici.name,
                             alpha = visit.type)) +
  geom_point(size = 3) +
  labs(y = "Patient", x = "Days from earliest sample") +
  scale_color_viridis_d(name = "Treatment", option = "turbo") +
  scale_shape(name = "PPI") +
  scale_alpha_manual(breaks = c("cycle", "study"), values = c(.4, 1), guide = "none") +
  theme_bw() 
ggsave("../figures/timeline_sample-points_treatment-ppi_days.png", height = 5, width = 5)
```