---
title: "Correlations with senescence"
output: html_document
date: '2022-10-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom)
library(glmm)
library(lme4)
library(lmerTest)
```

# Load data

```{r}
clin <- read.csv("T:/Labs/Spakowicz/fitness/data/derived/clinical-OC-matched_resolved_limited.csv",
                 stringsAsFactors = F)
clin.withdate <- read.csv("T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/CoRR5512FITNESSCalcu_DATA_2022-10-04_1152.csv", stringsAsFactors = F)
colnames(clin.withdate)[1] <- "id"

tsen <- read.csv("../data/Tcell-senescence.csv")
nano <- read.csv("../data/nanostring_extracted.csv")
```

# Format and analyses
```{r}
GA.score <- c("carg_score", "sppb_score", "blessed_score", "iadl_score", "promis_score")
nano.genes <- colnames(nano)[-c(1:2)]
```

```{r}
formatForCorr <- function(){
  modin <- clin %>%
    select(c("patient.id", "redcap_event_name", GA.score)) %>%
    mutate(visit = case_when(redcap_event_name == "study_visit_1_arm_2" ~ "SV1",
                             redcap_event_name == "study_visit_2_arm_2" ~ "SV2",
                             redcap_event_name == "study_visit_3_arm_2" ~ "SV3",
                             redcap_event_name == "study_visit_4_arm_2" ~ "SV4")) %>%
    inner_join(tsen) %>%
    group_by(patient.id) %>%
    filter(visit == min(visit))
  
  return(modin)
}

TcellGAcorrs <- function(){
  modin <- formatForCorr()
  
  corr.res <- lapply(GA.score, function(x) 
    cor.test(modin[[x]],
             modin[["Tcell.Senescence"]], 
             method = "spearman") %>%
                       tidy() %>%
                       mutate(GeriatricAssessment = x)) %>%
    bind_rows()
  
  return(corr.res)
}

```

```{r}
formatForCorrGene <- function(){
    modin <- clin %>%
    select(c("patient.id", "redcap_event_name", GA.score)) %>%
    mutate(visit = case_when(redcap_event_name == "study_visit_1_arm_2" ~ "SV1",
                             redcap_event_name == "study_visit_2_arm_2" ~ "SV2",
                             redcap_event_name == "study_visit_3_arm_2" ~ "SV3",
                             redcap_event_name == "study_visit_4_arm_2" ~ "SV4")) %>%
    inner_join(nano) %>%
    group_by(patient.id) %>%
    filter(visit == min(visit))
  
  return(modin)
}

GeneGAcorrs <- function(){
  modin <- formatForCorrGene()
  
  corr.res <- lapply(GA.score, function(x) 
    lapply(nano.genes, function(y) cor.test(modin[[x]], modin[[y]], 
                                            method = "spearman") %>%
             tidy() %>%
             mutate(GeriatricAssessment = x, gene = y) %>%
             bind_rows())) %>%
    bind_rows()
  
  return(corr.res)
}
```

```{r}
getVisitDays <- function(){
  enroll <- clin.withdate %>%
    select(id, sid_2, enrollment_date) %>%
    filter(enrollment_date != "") %>%
    mutate(enrollment_date = as.Date(enrollment_date))
  
  tmp <- clin.withdate %>%
    select(id, redcap_event_name, hem_lab_date) %>%
    # pivot_longer(-sid_2, names_to = "vis", values_to = "date") %>%
    filter(hem_lab_date != "") %>%
    mutate(hem_lab_date = as.Date(hem_lab_date)) %>%
    left_join(enroll) %>%
    mutate(elapsed.days = as.numeric(hem_lab_date-enrollment_date)) %>%
    mutate(visit = case_when(grepl("visit_1", redcap_event_name) ~ "SV1",
                             grepl("visit_2", redcap_event_name) ~ "SV2",
                             grepl("visit_3", redcap_event_name) ~ "SV3",
                             grepl("visit_4", redcap_event_name) ~ "SV4")) %>%
    rename("patient.id" = "sid_2")

  return(tmp)

}

formatForCorrLong <- function(){
  eldays <- getVisitDays()
  
  modin <- clin %>%
    select(c("patient.id", "redcap_event_name", GA.score)) %>%
    mutate(visit = case_when(redcap_event_name == "study_visit_1_arm_2" ~ "SV1",
                             redcap_event_name == "study_visit_2_arm_2" ~ "SV2",
                             redcap_event_name == "study_visit_3_arm_2" ~ "SV3",
                             redcap_event_name == "study_visit_4_arm_2" ~ "SV4")) %>%
    inner_join(tsen) %>%
    left_join(nano) %>%
    left_join(eldays) %>%
    mutate(patient.id = as.character(patient.id))
  
  
  modin.scale <- modin %>%
    select(c("Tcell.Senescence", nano.genes, GA.score[2:5])) %>%
    scale()
  
  modin.scale.recomb <- modin %>%
    select(-c("Tcell.Senescence", nano.genes, GA.score[2:5]))
  modin.scale.recomb <- bind_cols(modin.scale.recomb, modin.scale)
  
  return(modin.scale.recomb)
}


long_mods <-function(outcome, mics.vec){
  
  mods <- lapply(mics.vec, function(x) 
    try(summary(lmer(formula = as.formula(paste0(outcome,
                                                 " ~ ",
                                                 x,
                                                 " + elapsed.days +",
                                                 " (1|patient.id)")),
                     data = modelin))$coefficients %>%
          as.data.frame() %>%
          rownames_to_column(var = "Gene") %>%
          filter(Gene == x) %>%
          mutate(score = outcome)))
  mods.clean <- bind_rows(mods) %>%
    arrange(`Pr(>|t|)`)
  return(mods.clean)
}
```

# Visualize

```{r}
GA.res <- TcellGAcorrs()

GA.res
```

```{r}
gene.GA.res <- GeneGAcorrs() %>%
  mutate(padj = p.adjust(p.value, method = "fdr"))
write.csv(gene.GA.res, "../data/correlations_GA-genes.csv", row.names = F)
```

```{r}
modelin <- formatForCorrLong()
GA.long <- lapply(GA.score[2:5], function(x) long_mods(x, c("Tcell.Senescence", nano.genes))) %>%
  bind_rows() %>%
  mutate(padj = p.adjust(`Pr(>|t|)`, method = "fdr"))

write.csv(GA.long, "../data/longitudinal-modeling_nanostring.csv", row.names = F)
```

```{r scatter blessed Tcell}
scatterin <- formatForCorr()
pval = GA.res %>%
  filter(GeriatricAssessment == "blessed_score") %>%
  select(p.value)
pval <- round(pval[1,1], 3)
scatterin %>%
  ggplot(aes(x = blessed_score, y = Tcell.Senescence)) +
  geom_point() +
  geom_text(inherit.aes = F, x = 7, y = .1, label = paste0("p.value = ",pval))+
  stat_smooth(method = "lm") +
  labs(x = "BLESSED") +
  theme_bw()
ggsave("../figures/scatterplot_Tcell-blessed.png")
```

# IADL plots

```{r get slope and intercept info}
test <- lmer(formula = as.formula(paste0("iadl_score",
                                         " ~ ",
                                         "LAG3",
                                         " + elapsed.days +",
                                         " (1|patient.id)")),
             data = modelin)
summary(test)

test <- lmer(formula = as.formula(paste0("iadl_score",
                                         " ~ ",
                                         "CD8A",
                                         " + elapsed.days +",
                                         " (1|patient.id)")),
             data = modelin)
summary(test)

```

```{r scatter IADL sig}
iadl.dat <- formatForCorrLong() %>%
  select(patient.id, redcap_event_name, elapsed.days, iadl_score, 
         CD8A, LAG3) %>%
  pivot_longer(c("CD8A", "LAG3"), names_to = "gene", values_to = "gene.exp")

iadl.dat %>%
  filter(gene == "LAG3") %>%
  ggplot(aes(x = iadl_score, y = gene.exp)) +
  geom_point() +
  geom_abline(slope = -0.192921, intercept = -0.159649) +
  labs(y = "LAG3") +
  theme_bw()
ggsave("../figures/scatter_iadl-lag3.png")

iadl.dat %>%
  filter(gene == "CD8A") %>%
  ggplot(aes(x = iadl_score, y = gene.exp)) +
  geom_point() +
  geom_abline(slope = -0.1881678, intercept = -0.1030304) +
  labs(y = "CD8A") +
  theme_bw()
ggsave("../figures/scatter_iadl-cd8a.png")


iadl.dat %>%
  ggplot(aes(x = iadl_score, y = gene.exp)) +
  facet_wrap(vars(gene)) +
  geom_point() +
  geom_abline(aes(slope = -0.1881678, intercept = -0.1030304),
              data = subset(iadl.dat, gene == "CD8A")) +
  geom_abline(aes(slope = -0.192921, intercept = -0.159649), 
              data = subset(iadl.dat, gene == "LAG3")) +
  labs(y = "Gene expression", x = "IADL") +
  theme_bw()
ggsave("../figures/scatterplot_iadl-cd81-lag3.png")
```

```{r iadl unscaled vis}
eldays <- getVisitDays()

iadl.dat.unscaled <- clin %>%
  select(c("patient.id", "redcap_event_name", GA.score)) %>%
  mutate(visit = case_when(
    redcap_event_name == "study_visit_1_arm_2" ~ "SV1",
    redcap_event_name == "study_visit_2_arm_2" ~ "SV2",
    redcap_event_name == "study_visit_3_arm_2" ~ "SV3",
    redcap_event_name == "study_visit_4_arm_2" ~ "SV4")) %>%
  inner_join(tsen) %>%
  left_join(nano) %>%
  left_join(eldays) %>%
  mutate(patient.id = as.character(patient.id)) %>%
  select(patient.id, redcap_event_name, elapsed.days, iadl_score, 
         CD8A, LAG3) %>%
  pivot_longer(c("CD8A", "LAG3"), names_to = "gene", values_to = "gene.exp")


iadl.dat.unscaled %>%
  ggplot(aes(x = iadl_score, y = gene.exp, group = gene)) +
  facet_wrap(vars(gene), scales = "free_y") +
  geom_point() +
  stat_smooth(method = "lm", color = "black") +
  # geom_abline(aes(slope = -0.1881678, intercept = -0.1030304),
  #             data = subset(iadl.dat, gene == "CD8A")) +
  # geom_abline(aes(slope = -0.192921, intercept = -0.159649), 
  #             data = subset(iadl.dat, gene == "LAG3")) +
  labs(y = "Gene expression", x = "IADL") +
  theme_bw()
ggsave("../figures/scatterplot_iadl-cd81-lag3_unscaled.png")
```