---
title: "Concomitant PPI"
author: "Rebecca Hoyd"
date: "7/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis)
library(readxl)
library(stringr)
library(lme4)
library(lmerTest)
library(broom)
library(rlist)
library(ggforce)
library(forcats)
source("00-paths.R")
```


# Load data

```{r}

clin <- read.csv(file.path(paths$t.drive, "data", "clinical-OC-matched_resolved_limited.csv"), stringsAsFactors = F)
clin.withdate <- read.csv(file.path(paths$controlled, "clinical-OC-matched_resolved.csv"), stringsAsFactors = F)

# studcy <- read_excel("../data/cycle_study-visit-tracker_v3.xlsx")
```


# Visualize timelines

```{r}
clin.filt.days <- clin%>%
  select("patient.id", "sequence.id", "redcap_event_name", 
         # "stool_sample_date", 
         "sppb_score", "promis_score") %>%
  group_by(patient.id) %>%
  ungroup() %>%
  filter(grepl("study", redcap_event_name)) %>%
  mutate(visit = gsub("study_visit_(\\d+)_arm_2", "\\1", redcap_event_name)) %>%
  select("patient.id", "sequence.id", "redcap_event_name", "visit",
         # "stool_sample_date", "earliest_day", "elapsed.days", 
         "sppb_score", "promis_score") %>%
  add_count(patient.id) %>%
  filter(n > 1)

clin.filt.days %>%
  ggplot(aes(x = visit,y = sppb_score, group = as.factor(patient.id), color = as.factor(patient.id))) +
  geom_line() +
  geom_point()
ggsave("../figures/timeline_sppb.png")

clin.filt.days %>%
  ggplot(aes(x = visit,y = promis_score, group = as.factor(patient.id), color = as.factor(patient.id))) +
  geom_line() +
  geom_point()
ggsave("../figures/timeline_promis.png")
```

```{r}
# ggplot(clin.timein.days, aes(x = elapsed.days, y = as.factor(ylabs), shape = as.factor(ppi), color = ici.name,
#                              alpha = visit.type)) +
#   geom_point(size = 3) +
#   labs(y = "Patient", x = "Days from earliest sample") +
#   scale_color_viridis_d(name = "Treatment", option = "turbo") +
#   scale_shape(name = "PPI") +
#   scale_alpha_manual(breaks = c("cycle", "study"), values = c(.4, 1), guide = FALSE) +
#   theme_bw() +
#   ggsave("../figures/timeline_sample-points_treatment-ppi_days.png", height = 5, width = 5)
```

# Set up modeling

## Get + format modelling data

```{r}
mics <- read.table("T:/Labs/Spakowicz/fitness/data/merged_metaphlan_output.txt", sep = "\t", header = T, stringsAsFactors = F)

mics.form <- mics %>%
  select(-NCBI_tax_id) %>%
  mutate(clade_name = make.names(clade_name)) %>%
  gather(-clade_name, key = "sequence.id", value = "RA") %>%
  spread(key = clade_name, value = RA)

mic.names <- colnames(mics.form[,-1])
```

```{r}
modelin <- clin.withdate %>%
  select(patient.id, redcap_event_name, sppb_score, promis_score, stool_sample_date, sequence.id) %>%
  filter(!is.na(sppb_score) &!is.na(stool_sample_date)) %>%
  mutate(stool_sample_date = as.Date(stool_sample_date)) %>%
  group_by(patient.id) %>%
  mutate(min.date = min(stool_sample_date)) %>%
  ungroup() %>%
  mutate(rel.date = as.numeric(stool_sample_date - min.date)) %>%
  left_join(mics.form)
  
```
## Modeling function


```{r}
long_mods <-function(outcome, mics.vec){
  
  mods <- lapply(mics.vec, function(x) try(summary(lmer(formula = as.formula(paste0(outcome,
                                                                                    " ~ ",
                                                                                    x,
                                                                                    " + rel.date + (1|patient.id)")),
                                                        data = modelin))$coefficients %>%
                                             as.data.frame() %>%
                                             rownames_to_column(var = "term") %>%
                                             mutate(microbe = x)))
  mods.clean <- bind_rows(mods) %>%
    arrange(`Pr(>|t|)`)
  return(mods.clean)
}
```

```{r}
sppb.mods <- long_mods("sppb_score", mic.names)
promis.mods <- long_mods("promis_score", mic.names)
```

```{r}
sppb.sig <- sppb.mods %>%
  filter(term == microbe & `Pr(>|t|)` < 0.05)
promis.sig <- promis.mods %>%
  filter(term == microbe & `Pr(>|t|)` < 0.05)

head(sppb.sig)
head(promis.sig)
```

```{r}
write.csv(sppb.sig, "../data/modelling_sppb-longitudinal_sig.csv", row.names = F)
write.csv(promis.sig, "../data/modelling_promis-longitudinal_sig.csv", row.names = F)
```

# Try plotting

```{r}
sppb.sig <- read.csv("../data/modelling_sppb-longitudinal_sig.csv", stringsAsFactors = F)
```

## Format data

```{r}
sppb.possig <- sppb.sig %>%
  filter(Estimate >= 0)

sppb.baseline <- modelin %>%
  filter(rel.date ==0) %>%
  mutate(sppb.baseline = sppb_score) %>%
  select(patient.id, sppb.baseline)

plotin <- modelin %>%
  select(c("patient.id", "sppb_score", "rel.date", sppb.sig$term)) %>%
  left_join(sppb.baseline) %>%
  mutate(sppb_norm = sppb_score - sppb.baseline) %>%
  select(-sppb_score, -sppb.baseline) %>%
  gather(c("sppb_norm", sppb.sig$term), key = "term", value = "count") %>%
  mutate(measure = ifelse(term == "sppb_norm", "SPPB", "Microbe"),
         effect.dir = ifelse(term %in% sppb.possig$term, "Positive",
                             ifelse(term == "sppb_norm", NA, "Negative"))) %>%
  arrange(rel.date)

sig.plot.ord <- sppb.sig %>%
  arrange(Estimate)
sig.plot.ord <- sig.plot.ord$term
```

```{r}
modelin %>%
  ggplot(aes(x = rel.date, y = sppb_score)) +
  geom_point()+
  stat_smooth() +
  ggsave("../figures/scatter_sppb-time.png")

modelin %>%
  ggplot(aes(x = rel.date)) +
  geom_histogram()

table(modelin$rel.date == 0)
```

# Plot as lines

```{r}
# saveRDS(plotin, "../data/sppb_longitudinal-lineplot-input.RDS")

plotin %>%
  ggplot(aes(x = rel.date, y = count, group = fct_relevel(term, sig.plot.ord), 
             color = effect.dir, fill = effect.dir)) +
  facet_col(vars(fct_relevel(measure, "SPPB")), scales = "free_y", space = "free") +
  # facet_col(vars(effect.dir), space = "free", scales = "free_y") +
  geom_point() +
  stat_smooth(alpha = .2) +
  # stat_smooth(aes(group = measure)) + 
  scale_color_viridis_d(aesthetics = c("color", "fill"), na.value = "grey50", name = "Effect \ndirection") +
  labs(x = "", y = "") + 
  theme_bw() +
  ggsave("../figures/sppb_longitudinal.png")
```

# Plot as lollipop

```{r}
choose.taxa <- c("k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Peptostreptococcaceae.g__Romboutsia",
                "k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Lachnospiraceae.g__Lachnoclostridium.s__Lachnoclostridium_sp_An138",
                "k__Bacteria.p__Firmicutes.c__Erysipelotrichia.o__Erysipelotrichales.f__Erysipelotrichaceae.g__Absiella",
                "k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Bacteroidaceae.g__Bacteroides.s__Bacteroides_stercorirosoris",
                "k__Bacteria.p__Firmicutes.c__Bacilli.o__Lactobacillales.f__Lactobacillaceae.g__Lactobacillus.s__Lactobacillus_rogosae", 
                "k__Bacteria.p__Candidatus_Melainabacteria")


lollipop.in <- sppb.sig %>%
  filter(term %in% choose.taxa) %>%
  mutate(display.name = gsub("_", " ", gsub(".*__(.*)", "\\1", term)),
         effect.dir = ifelse(term %in% sppb.possig$term, "Positive", "Negative")) %>%
  arrange(Estimate)
lolli.ord <- lollipop.in$display.name
```

```{r}
lollipop.in %>%
  ggplot(aes(x = Estimate, y = fct_relevel(display.name, lolli.ord),
             yend = fct_relevel(display.name, lolli.ord), color = effect.dir)) +
  geom_segment(xend = 0, color = "black") +
  geom_point(size = 5) +
  scale_color_viridis_d(name = "") +
  labs(x = "Effect size", y = "") +
  theme_bw() +
  ggsave("../figures/lollipop_sppb-longitudinal.png")
```
