---
title: "Diversity"
author: "Rebecca Hoyd"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(vegan)
```


# Load data

```{r}
mettab <- read.table("T:/Labs/Spakowicz/fitness/data/derived/merged_metaphlan_output.txt",
                     header = T, stringsAsFactors = F)
clin <- read.csv("T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/clinical-OC-matched_resolved.csv",
                 stringsAsFactors = F)
```

# Format

```{r}
div.in <- mettab %>%
  select(-NCBI_tax_id) %>%
  filter(grepl("s__", clade_name)) %>%
  column_to_rownames(var = "clade_name") %>%
  t()
```

# Calculate alpha div

```{r}
test <- diversity(div.in, index = "simpson")
```

```{r}
# DL017
test["FF05466606"]

# DL081
test["FF05466567"]
```

# Format and save

```{r}
div.tab <- test %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  rename("Simpson.div" = ".")

write.csv(div.tab, "../data/OC_simpson-diversity.csv")
```