---
title: "modeling toxicity with microbes"
output: html_document
date: '2022-10-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom)
library(ordinal)
```

# Load data

```{r}
clin <- read.csv("T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/CoRR5512FITNESSCalcu_DATA_2022-10-04_1152.csv", stringsAsFactors = F)
colnames(clin)[1] <- "id"

key <- read.csv("T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/key_fitness-microbe-clin.csv")

mics <- read.table("T:/Labs/Spakowicz/fitness/data/derived/merged_metaphlan_output.txt", header = T, sep = "\t")
```

# Format


```{r}
grabDates <- function(){
 enroll <- clin %>% 
   select(id, sid_2, enrollment_date) %>% 
   drop_na(sid_2)
 
 stool.date <- clin %>%
   select(id, redcap_event_name, stool_sample_date) %>%
   filter(stool_sample_date != "") %>%
   left_join(enroll) %>%
   mutate(enrollment_date = as.Date(enrollment_date),
          stool_sample_date = as.Date(stool_sample_date),
          elapsed.days = as.numeric(stool_sample_date -
                                     enrollment_date)) %>%
   select(id, sid_2, redcap_event_name, elapsed.days) %>%
   rename("patient.id" = "sid_2")
 
 return(stool.date)
}

grabTox <- function(){
  toxnest <- clin %>%
    filter(redcap_repeat_instrument == "adverse_events_and_toxicities_new") %>%
    select(id, redcap_event_name, tox_grade_new)
  
  tox.unnest <- toxnest %>%
    group_by(id, redcap_event_name) %>%
    summarise(tox_max_grade = max(tox_grade_new, na.rm = T)) %>%
    mutate(tox_max_grade = ifelse(tox_max_grade == -Inf, NA, tox_max_grade))
}

buildModelDat <- function(){
  toxdat <- grabTox()
  stool.date <- grabDates()
  mics.form <- mics %>%
    select(-NCBI_tax_id) %>%
    column_to_rownames(var = "clade_name") %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column(var = "sequence.id")
    
  names(mics.form) <- make.names(names(mics.form))
  micnames <- colnames(mics.form[,-1])
  
  modin <- key %>%
    left_join(toxdat) %>%
    left_join(stool.date) %>%
    mutate(tox_max_grade = replace_na(tox_max_grade, 0),
           grade3 = ifelse(tox_max_grade >= 3, 1,0),
           grade2 = ifelse(tox_max_grade >= 2, 1, 0)) %>%
    left_join(mics.form) %>%
    drop_na(k__Archaea)
  
  checkvar <- unlist(lapply(micnames, function(x) var(modin[[x]])))
  names(checkvar) <- micnames
  totest <- names(subset(checkvar, checkvar > 0))
  
  outls <- list(modin, totest)
  names(outls) <- c("ModDat", "mic.names")
  
  return(outls)
}

modelTox <- function(){
  modin <- buildModelDat() 
  
  modin$ModDat <- modin$ModDat %>%
    mutate(tox_max_grade = as.factor(tox_max_grade))
  
  tmp <- lapply(modin$mic.names, function(x)
    clm(formula = as.formula(paste("tox_max_grade ~", x, 
                                   "+ elapsed.days +",
                                   "(1|patient.id)")),
        data = modin$ModDat
    ) %>%
      tidy() %>%
      filter(term == x)) %>%
    bind_rows()
  
  return(tmp)
}
```


```{r}
buildModDatBase <- function(){
  toxdat <- grabTox()
  stool.date <- grabDates()
  mics.form <- mics %>%
    select(-NCBI_tax_id) %>%
    column_to_rownames(var = "clade_name") %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column(var = "sequence.id")
    
  names(mics.form) <- make.names(names(mics.form))
  micnames <- colnames(mics.form[,-1])
  
  modin <- key %>%
    left_join(toxdat) %>%
    left_join(stool.date) %>%
    group_by(patient.id) %>%
    mutate(max_toxgrade = max(tox_max_grade, na.rm = T)) %>%
    filter(elapsed.days == min(elapsed.days)) %>%
    mutate(max_toxgrade = replace_na(max_toxgrade, 0),
           grade3 = ifelse(max_toxgrade >= 3, 1,0),
           grade2 = ifelse(max_toxgrade >= 2, 1, 0)) %>%
    left_join(mics.form) %>%
    drop_na(k__Archaea)
  
  checkvar <- unlist(lapply(micnames, function(x) var(modin[[x]])))
  names(checkvar) <- micnames
  totest <- names(subset(checkvar, checkvar > 0))
  
  outls <- list(modin, totest)
  names(outls) <- c("ModDat", "mic.names")
  
  return(outls)
}

modelToxBase <- function(){
  modin <- buildModDatBase() 
  
  tmp <- lapply(modin$mic.names, function(x)
    glm(formula = as.formula(paste("grade2 ~", x)),
        data = modin$ModDat,
        family = "binomial"
    ) %>%
      tidy() %>%
      filter(term == x)) %>%
    bind_rows()
  
  return(tmp)
}

```
# Models


```{r}
tox.logreg <- modelTox()
write.csv(tox.logreg, "../data/modelling_toxicity-microbes_longitudinal-ordinal.csv",
          row.names = F)
```

```{r}
tox.base <- modelToxBase()
write.csv(tox.base, "../data/modelling_toxicity-microbes_baseline-logreg.csv",
          row.names = F)
```
# Vis
