---
title: "Concomitant PPI"
author: "Rebecca Hoyd"
date: "7/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(dplyr)
library(tidyr)
library(readxl)
library(stringr)
# source("00-paths.R")
```


# Load data

```{r}
controlled <- "T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca"

ICI.meds.raw <- read_excel("../data/FITNESS_TreatmentCategories_8.23.21.xlsx")

clin.withdate <- read.csv(file.path(controlled, "clinical-OC-matched_resolved.csv"), stringsAsFactors = F)

```

# Label ICI and collapse treatments

```{r}
ICI.meds <- ICI.meds.raw %>%
  rename(ici.nums = ...1,
         ici.name = `Category (chemo, chemo + io, io, targeted, targeted+chemo)`) %>%
  mutate(ici.name =str_replace_all(ici.name, "\\s", ""))
```

```{r}
# test <- colnames(clin)
# test[grep("the", test)]
# sort(test)

clin.filt <- clin.withdate %>%
  select("patient.id", "redcap_event_name", contains("tx_reg"))


patient.treatkey <- clin.filt %>%
  mutate(ici.nums = as.character(ifelse(!is.na(tx_reg_1_2), tx_reg_1_2, tx_reg_1))) %>%
  select(patient.id, redcap_event_name, ici.nums) %>%
  drop_na(ici.nums) %>%
  mutate(ici.nums = as.numeric(ici.nums)) %>%
  left_join(ICI.meds) %>%
  group_by(patient.id, ici.name) %>%
  tally() %>%
  pivot_wider(names_from = ici.name, values_from = n) %>%
  mutate(chemo_io = !is.na(`chemo+io`),
         io = !is.na(io),
         chemo = !is.na(chemo),
         targeted = !is.na(targeted),
         collapsed.treat = ifelse(chemo_io == T,
                                  ifelse(targeted == T, "chemo,io,targeted", "chemo,io"),
                                  ifelse(chemo == T,
                                         ifelse(io == T, "chemo,io", "chemo"),
                                         ifelse(io == T, "io", "targeted")))
         ) %>%
  select(patient.id, collapsed.treat) %>%
  rename("summarise_treatment" = "collapsed.treat")
 
write.csv(patient.treatkey, "../data/key_patient-summarised-treatment.csv", row.names = F)
```


