---
title: "Diversity and senescence"
output: html_document
date: '2022-09-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(tmesig)
```

# Load data

```{r}
clin <- read.csv("T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/clinical-OC-matched_resolved.csv",
                 stringsAsFactors = F)
nanostring <- read_excel("T:/Labs/Spakowicz/fitness/data/raw/nanostring/RoskoPresley_NanostringJune2022.xlsx", sheet = 3)
```

# Calculate T cell senescence

```{r}
nanostring.form <- nanostring[-(1:2),] %>%
  rename("Gene.Symbol" = "Probe Name") %>%
  select(-c("Annotation", "Accession #", "NS Probe ID", "Class Name",
            "Analyte Type", "% Samples above Threshold")) %>%
  mutate(across(contains("Presley"), as.numeric))
```

```{r}
sensgenes <- c("CDKN2A (p16)", "CDKN2A (ARF)", "B3GAT1", "KLRG1")

tsen <- calculateAvgZScore(nanostring.form, sensgenes) %>%
  rename("Tcell.Senescence" = "avg_z_score") %>%
  mutate(patient.id = gsub(".*_(.*) SV.*", "\\1", sample),
         visit = case_when(grepl("SV1", sample) ~ "SV1",
                           grepl("SV2", sample) ~ "SV2",
                           grepl("SV3", sample) ~ "SV3",
                           grepl("SV4", sample) ~ "SV4")) %>%
  select(-sample) %>%
  drop_na(visit)
```

# Save

```{r}
write.csv(tsen, "../data/Tcell-senescence.csv", row.names = F)
```

