---
title: "AACR A&C 2022 response deseq"
output: html_document
date: '2022-09-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

# Load data

```{r}
response <- read_excel("T:/Labs/Spakowicz/fitness/data/raw/FITNESS lung RECIST final collection.xlsx",
                       sheet = "Data collection",
                       col_names = F)

clin <- read.csv("T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/CoRR5512FITNESSCalcu_DATA_2022-10-04_1152.csv", stringsAsFactors = F)

idkeys.SpakPres <- lapply(1:2, function(x) read_excel(path =                                             "T:/Labs/Presley/FITNESS-lung/Microbiome- Rebecca/fitness_sample-matching/OSU-18055 shared patient log.xlsx",
                                             sheet = x))

patinfo <- read_excel("T:/Labs/Spakowicz/fitness/data/derived/TruDiagnostic Patient Info.xlsx")
```

# Format

## Response

```{r utility formatting}
extractRESCIST <- function(data){
  # Which rows contain our main info [patient and final recist?]
  recordlines <- grep("Record ID", data$...1)
  targetlines <- grep("Target Lesion Response", data$...1)
  
  # Which columns have recist in them?
  data.respcols <- data[, c(4,7,10,13)]
  colnames(data.respcols) <- c("Baseline", "month3", 
                               "month6", "month12")
  
  # Grab only rows/column combos with recist, then label with patient
  data.resprows <- data.respcols[targetlines,]
  data.resprows$patient.id <- data$...1[recordlines]
  
  # Minor formatting
  respdat.form <- data.resprows %>%
    mutate(patient.id = gsub("Record ID. ", "", patient.id)) %>%
    pivot_longer(-patient.id, names_to = "Timepoint",
                 values_to = "RECIST")
  
  return(respdat.form)

}

getIDKeys <- function(){
  idkeys.keyon <- lapply(idkeys.SpakPres, function(x) x[, 1:2])
  idkeys.form <- bind_rows(idkeys.keyon) %>%
    pivot_longer(-`study ID`, names_to = "sheet", values_to = "id") %>%
    mutate(patient.id = as.character(`study ID`)) %>%
    filter(!is.na(id)) %>%
    select(patient.id, id)
  return(idkeys.form)
}
```

```{r set up redcap data we want to deal with}
getCorrectColumns <- function(){
  response.form <- extractRESCIST(response) %>%
    distinct() %>%
    pivot_wider(names_from = Timepoint, values_from = RECIST) %>%
    select(-Baseline) %>%
    as.data.frame() 
  
  response.form$month3 <- lapply(response.form$month3, function(x) paste(x, collapse = ", "))
  response.form <- response.form %>%
    unnest(cols = c(month3, month6, month12))
  colnames(response.form)[2:4] <- paste0("RECIST_", colnames(response.form[2:4]))
  
  idkeys.form <- getIDKeys()
  
  colnames(clin)[1] <- "id"
  clin2 <- clin %>%
    mutate(hospital_yn = ifelse(transplant_admiss_date!= "", "y", "n")) %>%
    select(id, redcap_event_name, redcap_repeat_instance,redcap_repeat_instrument, age, sex, offstudy_reason, 
           carg_score, sppb_score, promis_score, comorb_score,
           mental_health, bmi, ecog, lung_cancer_type,iadl_score,
           drugsinreg_pharm, hospital_yn, mhi_score, blessed_score,
           contains("tox")) %>%
    select(-contains("date")) %>%
    left_join(idkeys.form) %>%
    drop_na(patient.id) %>%
    distinct() %>%
    left_join(response.form) %>%
    select(-id) %>%
    select(patient.id, everything()) %>%
    as.data.frame()
  
  return(clin2)
}

getCorrectRows <- function(){
  patinfo.red <- patinfo %>%
    rename("patient.id" = "Study ID") %>%
    select(patient.id,Timepoint, `Accession #`)
  
  clin3 <- getCorrectColumns() %>%
    mutate(Timepoint = case_when(grepl("study_visit_1", redcap_event_name) ~ "SV1",
                                 grepl("study_visit_2", redcap_event_name) ~ "SV2",
                                 grepl("study_visit_3", redcap_event_name) ~ "SV3",
                                 grepl("study_visit_4", redcap_event_name) ~ "SV4",))
  patmatched <- patinfo.red %>%
    inner_join(clin3) %>%
    select(-Timepoint)
  
  return(patmatched)
}
```

```{r handle unnesting redcap}
reduceNest <- function(nested){
  unused.cols <- unlist(lapply(nested, function(x) all(is.na(x)|x=="")))
  unused.cols <- names(unused.cols)[unused.cols == T]
  
  lessnest <- nested %>%
    select(-unused.cols)
}

redcapUnNest <- function(){
  tmp <- getCorrectRows()
  
  notnested <- tmp %>%
    filter(redcap_repeat_instrument == "")
  notnested.dropcols <- reduceNest(notnested) %>%
    select(-contains("tox"))
  
  pharmnest <- tmp %>%
    filter(redcap_repeat_instrument == "pharmacist_rdi_form")
  fixpharm <- reduceNest(pharmnest)
  
  # Only dealing with requested columns
  toxnest <- tmp %>%
    filter(redcap_repeat_instrument != "pharmacist_rdi_form") %>%
    select(patient.id, redcap_event_name, tox_doselimiting_new, tox_onset_new2,
           tox_end_new2, tox_gradechange_new, tox_grade_new, tox_atrributable_new)
  
  tox.unnest <- toxnest %>%
    group_by(patient.id, redcap_event_name) %>%
    summarise(tox_doselimiting = any(tox_doselimiting_new == 1),
              tox_gradechange = any(tox_gradechange_new == 1),
              tox_max_grade = max(tox_grade_new, na.rm = T)) %>%
    mutate(tox_max_grade = ifelse(tox_max_grade == -Inf, NA, tox_max_grade))
  
  checkmaxatt <- tox.unnest %>%
    select(patient.id, redcap_event_name, tox_max_grade) %>%
    mutate(tox_grade_new = tox_max_grade) %>%
    left_join(toxnest) %>%
    group_by(patient.id, redcap_event_name, tox_max_grade) %>%
    summarise(tox_maxgrade_attributable = max(tox_atrributable_new, na.rm = T)) %>%
    mutate(tox_maxgrade_attributable = ifelse(tox_maxgrade_attributable == -Inf, NA,
                                              tox_maxgrade_attributable))
  
  fixtox <- tox.unnest %>%
    left_join(checkmaxatt)
  
  tmp.unnested <- notnested.dropcols %>%
    left_join(fixpharm) %>%
    left_join(fixtox)
  
  any(duplicated(tmp.unnested$`Accession #`))
  
  return(tmp.unnested)
}
```



# Save


```{r}
data.for.tru <- redcapUnNest()
write.csv(data.for.tru, "../data/clinical_for-TruDiag.csv", row.names = F)
```

```{r save RECIst too}
response.form <- extractRESCIST(response) %>%
  distinct() %>%
  pivot_wider(names_from = Timepoint, values_from = RECIST) %>%
  select(-Baseline) %>%
  as.data.frame() 

response.form$month3 <- lapply(response.form$month3, function(x) paste(x, collapse = ", "))
response.form <- response.form %>%
  unnest(cols = c(month3, month6, month12))

# patient 4035 had 2 recist measures, we replace the conflicting results with the measurement that best reflects the study timeline.
response.form$month3 <- gsub("PR, PD", "PD", response.form$month3)
colnames(response.form)[2:4] <- paste0("RECIST_", colnames(response.form[2:4]))

write.csv(response.form, "../data/RECIST.csv", row.names = F)
```

