---
title: "baseline sample matching"
author: "Rebecca Hoyd"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readxl)
library(tidyr)
library(writexl)
source("00-paths.R")
```

This document is just to check which microbe samples match with which visits we have info on based on the data available in redcapp. I am not making any final objects at this point.
# Load data

```{r}
CoRR <- read.csv(file.path(paths$controlled,
                                   "CoRR5512FITNESSCalcu-FullLungDataset2921_DATA_2021-02-09_1311.csv"),
                  stringsAsFactors = F)


idkeys.SpakPres <- lapply(1:2, function(x) read_excel(path = file.path(paths$controlled, 
                                                                       "OSU-18055 shared patient log.xlsx"),
                                             sheet = x))

idkeys.SpakOne <- read.csv(file.path(paths$t.drive, "data", "onecodex", "One Codex Sample Sheet.csv"),
                           stringsAsFactors = F) %>%
  select(Name, External.Sample.ID)
```

# Keys formatting
```{r}
idkeys.keyon <- lapply(idkeys.SpakPres, function(x) x[, 1:2])
idkeys.form <- bind_rows(idkeys.keyon) %>%
  gather(-`study ID`, key = "sheet", value = "id") %>%
  rename("patient.id" = "study ID") %>%
  filter(!is.na(id))

patkey <- idkeys.SpakOne %>%
  # filter(!is.na(Order)) %>%
  rename('sequence.id' = "External.Sample.ID",
         "Sample" = "Name") %>%
  separate(Sample, sep = "\\.", into = c("patient.id", "Sample")) %>%
  mutate(year = paste0(20, substr(Sample, 1, 2)),
         month = substr(Sample, 3, 4),
         day = substr(Sample, 5,6),
         date = as.POSIXct(paste(year, month, day, sep = "/"), format = "%Y/%m/%d"),
         patient.id = as.numeric(patient.id)) %>%
  select(sequence.id, patient.id, date) %>%
  mutate(stool_sample_date = as.character(date))

```

```{r}
test <- colnames(CoRR)
test[grep("carg", test)]


CoRR.reduced <- CoRR %>%
  filter(is.na(redcap_repeat_instance)) %>%
  select(id, redcap_event_name, start_date_1, tox_onset_new2, stool_sample_date)
```

# Try some matches

## Check matching capability

```{r}
combined_obj <- CoRR.reduced %>%
  left_join(idkeys.form) %>%
  select(-sheet) %>%
  left_join(patkey) %>%
  select(id, patient.id, redcap_event_name, stool_sample_date, sequence.id)

stooldate.success <- combined_obj %>%
  filter(!is.na(sequence.id))

stooldate.redfail <- combined_obj %>%
  filter(is.na(sequence.id) & stool_sample_date != "")

stooldate.micfail <- patkey %>%
  filter(!sequence.id %in% stooldate.success$sequence.id) %>%
  left_join(idkeys.form) %>%
  select(-sheet)

stoolmatch.res <- list(stooldate.success, stooldate.redfail, stooldate.micfail)
names(stoolmatch.res) <- c("Successfull.matches", "Redcap.unmatched", "Microbes.unmathced")
```

## Use successful matches

```{r}
clin.successmatch <- stooldate.success %>%
  left_join(CoRR)  %>%
  select(-contains("date"), -"last_name", -"labname", -"last_followup", -"lab_collection", -"id",
         -"dob", -"dodx", -"mrn_id")
```

# Write results

```{r}
write_xlsx(stoolmatch.res, file.path(paths$controlled, "test-longitudinal-matching_OneCodex.xlsx"))
write.csv(clin.successmatch, file.path(paths$t.drive, "data", "clinical-with-OCids_limited.csv"))
```

# Just CARG scores for Ryan

```{r}
clin.successmatch %>%
  select(patient.id, redcap_event_name, sequence.id, carg_score) %>%
  write.csv(file.path(paths$t.drive, "data", "matched-carg-scores.csv"), row.names = F)
```
