---
title: "Visualizing longitudinal results"
author: "Rebecca Hoyd"
date: "1/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
source("00-paths.R")
```

# Load data

```{r}
mics <- read.table("T:/Labs/Spakowicz/fitness/data/merged_metaphlan_output.txt", sep = "\t", header = T, stringsAsFactors = F)
clin.withdate <- read.csv(file.path(paths$controlled, "clinical-OC-matched_resolved.csv"), stringsAsFactors = F)

sppb.mods <- read.csv("../data/model_long-treat_sppb.csv", stringsAsFactors = F)
promis.mods <- read.csv("../data/model_long-treat_promis.csv", stringsAsFactors = F)
iadl.mods <- read.csv("../data/model_long-treat_iadl.csv", stringsAsFactors = F)
tug.mods <- read.csv("../data/model_long-treat_timed-up-go.csv", stringsAsFactors = F)
```

# Prepare dataframe with all points

```{r}
mics.form <- mics %>%
  select(-NCBI_tax_id) %>%
  mutate(clade_name = make.names(clade_name)) %>%
  gather(-clade_name, key = "sequence.id", value = "RA") %>%
  spread(key = clade_name, value = RA)

mic.names <- colnames(mics.form[,-1])

modelin <- clin.withdate %>%
  select(patient.id, redcap_event_name, sppb_score, iadl_score,
         promis_score, tug, stool_sample_date, sequence.id) %>%
  filter(!is.na(sppb_score) &!is.na(stool_sample_date)) %>%
  mutate(stool_sample_date = as.Date(stool_sample_date)) %>%
  group_by(patient.id) %>%
  mutate(min.date = min(stool_sample_date)) %>%
  ungroup() %>%
  mutate(rel.date = as.numeric(stool_sample_date - min.date)) %>%
  left_join(mics.form)
  
```

# Format significant models for plots

```{r formatting functions}
format_for_long <- function(score.plotname, score.varname, score.mods){
  score.sig <- score.mods %>%
    filter(Pr...t.. < 0.05)
  score.possig <- score.sig %>%
    filter(Estimate >= 0)
  
  score.baseline <- modelin %>%
    filter(rel.date ==0) %>%
    rename('score.baseline' = {{score.varname}}) %>%
    select(patient.id, score.baseline)
  
  plotin <- modelin %>%
    rename("score" = {{score.varname}}) %>%
    select(c("patient.id", "score", "rel.date", score.sig$microbe)) %>%
    left_join(score.baseline) %>%
    mutate(score_norm = score - score.baseline) %>%
    select(-score, -score.baseline) %>%
    gather(c("score_norm", score.sig$microbe), key = "term", value = "count") %>%
    mutate(measure = ifelse(term == "score_norm", score.plotname, "Microbe"),
           effect.dir = ifelse(term %in% score.possig$microbe, "Positive",
                               ifelse(term == "score_norm", NA, "Negative"))) %>%
    arrange(rel.date)
  
  sig.plot.ord <- score.sig %>%
    arrange(Estimate)
  sig.plot.ord <- sig.plot.ord$microbe
  
  output <- list(plotin, sig.plot.ord)
  names(output) <- c("plot.data", "microbe.order")
  return(output)
}

format_for_lolli <- function(score.sig, choose.taxa){
  
  lollipop.in <- score.sig %>%
    filter(microbe %in% choose.taxa) %>%
    mutate(display.name = gsub("_", " ", gsub(".*__(.*)", "\\1", microbe)),
           effect.dir = ifelse(Estimate >= 0, "Positive", "Negative")) %>%
    arrange(Estimate) %>%
    mutate(display.name.break = gsub("^(\\w+)\\s(.*)$", "\\1\n\\2", display.name))
  lolli.ord <- lollipop.in$display.name.break
  
  output <- list(lollipop.in, lolli.ord)
  names(output) <- c("plot.data", "microbe.order")
  
  return(output)
}
```

```{r format for longitudinal plots}
sppb.longplot <- format_for_long("SPPB", "sppb_score", sppb.mods)
iadl.longplot <- format_for_long("IADL", "iadl_score", iadl.mods)
promis.longplot <- format_for_long("PROMIS", "promis_score", promis.mods)
tug.longplot <- format_for_long("TimedUpGo", "tug", tug.mods)
```

```{r format for lollipops}
sppb.sig <- sppb.mods %>%
  filter(Pr...t.. < 0.05)
sppb.taxa <- c("k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Peptostreptococcaceae.g__Romboutsia.s__Romboutsia_ilealis",
                "k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Lachnospiraceae.g__Lachnoclostridium.s__Lachnoclostridium_sp_An138",
                "k__Bacteria.p__Firmicutes.c__Erysipelotrichia.o__Erysipelotrichales.f__Erysipelotrichaceae.g__Absiella.s__Absiella_dolichum",
                "k__Bacteria.p__Candidatus_Melainabacteria.c__Candidatus_Melainabacteria_unclassified.o__Candidatus_Gastranaerophilales.f__Candidatus_Gastranaerophilales_unclassified.g__Candidatus_Gastranaerophilales_unclassified.s__Candidatus_Gastranaerophilales_bacterium",
                "k__Bacteria.p__Firmicutes.c__Bacilli.o__Lactobacillales.f__Lactobacillaceae.g__Lactobacillus.s__Lactobacillus_rogosae", 
                "k__Viruses.p__Viruses_unclassified.c__Viruses_unclassified.o__Caudovirales.f__Caudovirales_unclassified.g__Caudovirales_unclassified.s__Enterobacteria_phage_P4")

iadl.sig <- iadl.mods %>%
  filter(Pr...t.. < 0.05)
iadl.taxa <- c("k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Peptostreptococcaceae.g__Romboutsia.s__Romboutsia_ilealis",
                "k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Lachnospiraceae.g__Lachnoclostridium.s__Lachnoclostridium_sp_An138",
                "k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Clostridiales_unclassified.g__Clostridiales_unclassified.s__Clostridiales_bacterium_CHKCI006",
                "k__Bacteria.p__Candidatus_Melainabacteria.c__Candidatus_Melainabacteria_unclassified.o__Candidatus_Gastranaerophilales.f__Candidatus_Gastranaerophilales_unclassified.g__Candidatus_Gastranaerophilales_unclassified.s__Candidatus_Gastranaerophilales_bacterium",
                "k__Bacteria.p__Firmicutes.c__Bacilli.o__Lactobacillales.f__Lactobacillaceae.g__Lactobacillus.s__Lactobacillus_rogosae", 
                "k__Viruses.p__Viruses_unclassified.c__Viruses_unclassified.o__Caudovirales.f__Caudovirales_unclassified.g__Caudovirales_unclassified.s__Enterobacteria_phage_P4")

promis.sig <- promis.mods %>%
  filter(Pr...t.. < 0.05)
promis.taxa <- c("k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Eubacteriaceae.g__Eubacterium.s__Eubacterium_sp_CAG_274",
                "	k__Bacteria.p__Firmicutes.c__Erysipelotrichia.o__Erysipelotrichales.f__Erysipelotrichaceae.g__Holdemania.s__Holdemania_filiformis",
                "k__Viruses.p__Viruses_unclassified.c__Viruses_unclassified.o__Caudovirales.f__Siphoviridae.g__N15virus.s__Escherichia_virus_N15",
                "k__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Ruminococcaceae.g__Ruminococcaceae_unclassified.s__Ruminococcaceae_bacterium_D16",
                "k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Rikenellaceae.g__Alistipes.s__Alistipes_finegoldi", 
                "k__Bacteria.p__Firmicutes.c__Bacilli.o__Lactobacillales.f__Streptococcaceae.g__Streptococcus")



sppb.lolli <- format_for_lolli(sppb.sig, sppb.taxa)
promis.lolli <- format_for_lolli(promis.sig, promis.taxa)
iadl.lolli <- format_for_lolli(iadl.sig, iadl.taxa)
```

# Longitudinal points with stat_smooth

```{r}
long_plot <- function(plot.data, microbe.order, score.name){
  plot.data %>%
  ggplot(aes(x = rel.date, y = count, group = fct_relevel(term, microbe.order), 
             color = effect.dir, fill = effect.dir)) +
  facet_col(vars(fct_relevel(measure, score.name)), scales = "free_y", space = "free") +
  # facet_col(vars(effect.dir), space = "free", scales = "free_y") +
  geom_point() +
  stat_smooth(alpha = .2) +
  # stat_smooth(aes(group = measure)) + 
  scale_color_viridis_d(aesthetics = c("color", "fill"), na.value = "grey50", name = "Effect \ndirection") +
  labs(x = "", y = "") + 
  theme_bw()
}
```


```{r}
long_plot(sppb.longplot$plot.data, sppb.longplot$microbe.order, "SPPB")

ggsave("../figures/longitudinal_fixeffect_SPPB.svg",
       height = 3, width = 4)

```

```{r}
long_plot(iadl.longplot$plot.data, iadl.longplot$microbe.order, "IADL")

ggsave("../figures/longitudinal_fixeffect_IADL.svg",
       height = 3, width = 4)
```

```{r}
long_plot(promis.longplot$plot.data, promis.longplot$microbe.order, "PROMIS")

ggsave("../figures/longitudinal_fixeffect_PROMIS.svg",
       height = 3, width = 4)
```

```{r}
long_plot(tug.longplot$plot.data, tug.longplot$microbe.order, "TimedUpGo")

ggsave("../figures/longitudinal_fixeffect_TUG.svg",
       height = 3, width = 4)
```


# Lollipops

```{r}
plot_lollipop <- function(plot.data, microbe.order){
  plot.data %>%
  ggplot(aes(x = Estimate, y = fct_relevel(display.name.break, microbe.order),
             yend = fct_relevel(display.name.break, microbe.order), color = effect.dir)) +
  geom_segment(xend = 0, color = "black") +
  geom_point(size = 5) +
  scale_color_viridis_d(name = "") +
  labs(x = "Effect size", y = "") +
  theme_bw() 
}
```

```{r}
plot_lollipop(sppb.lolli$plot.data, sppb.lolli$microbe.order)
ggsave("../figures/lollipop_long-fixef_sppb.svg", height = 3, width = 4)
```

```{r}
plot_lollipop(promis.lolli$plot.data, promis.lolli$microbe.order)
ggsave("../figures/lollipop_long-fixef_promis.svg", height = 3, width = 4)
```

```{r}
plot_lollipop(iadl.lolli$plot.data, iadl.lolli$microbe.order)
ggsave("../figures/lollipop_long-fixef_iadl.svg", height = 3, width = 4)
```
